// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: s2/cs_gameevents.proto

package msgs2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ECsgoGameEvents int32

const (
	ECsgoGameEvents_GE_PlayerAnimEventId ECsgoGameEvents = 450
	ECsgoGameEvents_GE_RadioIconEventId  ECsgoGameEvents = 451
	ECsgoGameEvents_GE_FireBulletsId     ECsgoGameEvents = 452
)

// Enum value maps for ECsgoGameEvents.
var (
	ECsgoGameEvents_name = map[int32]string{
		450: "GE_PlayerAnimEventId",
		451: "GE_RadioIconEventId",
		452: "GE_FireBulletsId",
	}
	ECsgoGameEvents_value = map[string]int32{
		"GE_PlayerAnimEventId": 450,
		"GE_RadioIconEventId":  451,
		"GE_FireBulletsId":     452,
	}
)

func (x ECsgoGameEvents) Enum() *ECsgoGameEvents {
	p := new(ECsgoGameEvents)
	*p = x
	return p
}

func (x ECsgoGameEvents) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECsgoGameEvents) Descriptor() protoreflect.EnumDescriptor {
	return file_s2_cs_gameevents_proto_enumTypes[0].Descriptor()
}

func (ECsgoGameEvents) Type() protoreflect.EnumType {
	return &file_s2_cs_gameevents_proto_enumTypes[0]
}

func (x ECsgoGameEvents) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ECsgoGameEvents) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ECsgoGameEvents(num)
	return nil
}

// Deprecated: Use ECsgoGameEvents.Descriptor instead.
func (ECsgoGameEvents) EnumDescriptor() ([]byte, []int) {
	return file_s2_cs_gameevents_proto_rawDescGZIP(), []int{0}
}

type CMsgTEPlayerAnimEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *uint32                `protobuf:"fixed32,1,opt,name=player,def=16777215" json:"player,omitempty"`
	Event         *uint32                `protobuf:"varint,2,opt,name=event" json:"event,omitempty"`
	Data          *int32                 `protobuf:"varint,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgTEPlayerAnimEvent fields.
const (
	Default_CMsgTEPlayerAnimEvent_Player = uint32(16777215)
)

func (x *CMsgTEPlayerAnimEvent) Reset() {
	*x = CMsgTEPlayerAnimEvent{}
	mi := &file_s2_cs_gameevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgTEPlayerAnimEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgTEPlayerAnimEvent) ProtoMessage() {}

func (x *CMsgTEPlayerAnimEvent) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_gameevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgTEPlayerAnimEvent.ProtoReflect.Descriptor instead.
func (*CMsgTEPlayerAnimEvent) Descriptor() ([]byte, []int) {
	return file_s2_cs_gameevents_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgTEPlayerAnimEvent) GetPlayer() uint32 {
	if x != nil && x.Player != nil {
		return *x.Player
	}
	return Default_CMsgTEPlayerAnimEvent_Player
}

func (x *CMsgTEPlayerAnimEvent) GetEvent() uint32 {
	if x != nil && x.Event != nil {
		return *x.Event
	}
	return 0
}

func (x *CMsgTEPlayerAnimEvent) GetData() int32 {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return 0
}

type CMsgTERadioIcon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *uint32                `protobuf:"fixed32,1,opt,name=player,def=16777215" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgTERadioIcon fields.
const (
	Default_CMsgTERadioIcon_Player = uint32(16777215)
)

func (x *CMsgTERadioIcon) Reset() {
	*x = CMsgTERadioIcon{}
	mi := &file_s2_cs_gameevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgTERadioIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgTERadioIcon) ProtoMessage() {}

func (x *CMsgTERadioIcon) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_gameevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgTERadioIcon.ProtoReflect.Descriptor instead.
func (*CMsgTERadioIcon) Descriptor() ([]byte, []int) {
	return file_s2_cs_gameevents_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgTERadioIcon) GetPlayer() uint32 {
	if x != nil && x.Player != nil {
		return *x.Player
	}
	return Default_CMsgTERadioIcon_Player
}

type CMsgTEFireBullets struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Origin              *CMsgVector            `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Angles              *CMsgQAngle            `protobuf:"bytes,2,opt,name=angles" json:"angles,omitempty"`
	WeaponId            *uint32                `protobuf:"varint,3,opt,name=weapon_id,json=weaponId,def=16777215" json:"weapon_id,omitempty"`
	Mode                *uint32                `protobuf:"varint,4,opt,name=mode" json:"mode,omitempty"`
	Seed                *uint32                `protobuf:"varint,5,opt,name=seed" json:"seed,omitempty"`
	Player              *uint32                `protobuf:"fixed32,6,opt,name=player,def=16777215" json:"player,omitempty"`
	Inaccuracy          *float32               `protobuf:"fixed32,7,opt,name=inaccuracy" json:"inaccuracy,omitempty"`
	RecoilIndex         *float32               `protobuf:"fixed32,8,opt,name=recoil_index,json=recoilIndex" json:"recoil_index,omitempty"`
	Spread              *float32               `protobuf:"fixed32,9,opt,name=spread" json:"spread,omitempty"`
	SoundType           *int32                 `protobuf:"varint,10,opt,name=sound_type,json=soundType" json:"sound_type,omitempty"`
	ItemDefIndex        *uint32                `protobuf:"varint,11,opt,name=item_def_index,json=itemDefIndex" json:"item_def_index,omitempty"`
	SoundDspEffect      *uint32                `protobuf:"fixed32,12,opt,name=sound_dsp_effect,json=soundDspEffect" json:"sound_dsp_effect,omitempty"`
	EntOrigin           *CMsgVector            `protobuf:"bytes,13,opt,name=ent_origin,json=entOrigin" json:"ent_origin,omitempty"`
	NumBulletsRemaining *uint32                `protobuf:"varint,14,opt,name=num_bullets_remaining,json=numBulletsRemaining" json:"num_bullets_remaining,omitempty"`
	AttackType          *uint32                `protobuf:"varint,15,opt,name=attack_type,json=attackType" json:"attack_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

// Default values for CMsgTEFireBullets fields.
const (
	Default_CMsgTEFireBullets_WeaponId = uint32(16777215)
	Default_CMsgTEFireBullets_Player   = uint32(16777215)
)

func (x *CMsgTEFireBullets) Reset() {
	*x = CMsgTEFireBullets{}
	mi := &file_s2_cs_gameevents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgTEFireBullets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgTEFireBullets) ProtoMessage() {}

func (x *CMsgTEFireBullets) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_gameevents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgTEFireBullets.ProtoReflect.Descriptor instead.
func (*CMsgTEFireBullets) Descriptor() ([]byte, []int) {
	return file_s2_cs_gameevents_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgTEFireBullets) GetOrigin() *CMsgVector {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *CMsgTEFireBullets) GetAngles() *CMsgQAngle {
	if x != nil {
		return x.Angles
	}
	return nil
}

func (x *CMsgTEFireBullets) GetWeaponId() uint32 {
	if x != nil && x.WeaponId != nil {
		return *x.WeaponId
	}
	return Default_CMsgTEFireBullets_WeaponId
}

func (x *CMsgTEFireBullets) GetMode() uint32 {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return 0
}

func (x *CMsgTEFireBullets) GetSeed() uint32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *CMsgTEFireBullets) GetPlayer() uint32 {
	if x != nil && x.Player != nil {
		return *x.Player
	}
	return Default_CMsgTEFireBullets_Player
}

func (x *CMsgTEFireBullets) GetInaccuracy() float32 {
	if x != nil && x.Inaccuracy != nil {
		return *x.Inaccuracy
	}
	return 0
}

func (x *CMsgTEFireBullets) GetRecoilIndex() float32 {
	if x != nil && x.RecoilIndex != nil {
		return *x.RecoilIndex
	}
	return 0
}

func (x *CMsgTEFireBullets) GetSpread() float32 {
	if x != nil && x.Spread != nil {
		return *x.Spread
	}
	return 0
}

func (x *CMsgTEFireBullets) GetSoundType() int32 {
	if x != nil && x.SoundType != nil {
		return *x.SoundType
	}
	return 0
}

func (x *CMsgTEFireBullets) GetItemDefIndex() uint32 {
	if x != nil && x.ItemDefIndex != nil {
		return *x.ItemDefIndex
	}
	return 0
}

func (x *CMsgTEFireBullets) GetSoundDspEffect() uint32 {
	if x != nil && x.SoundDspEffect != nil {
		return *x.SoundDspEffect
	}
	return 0
}

func (x *CMsgTEFireBullets) GetEntOrigin() *CMsgVector {
	if x != nil {
		return x.EntOrigin
	}
	return nil
}

func (x *CMsgTEFireBullets) GetNumBulletsRemaining() uint32 {
	if x != nil && x.NumBulletsRemaining != nil {
		return *x.NumBulletsRemaining
	}
	return 0
}

func (x *CMsgTEFireBullets) GetAttackType() uint32 {
	if x != nil && x.AttackType != nil {
		return *x.AttackType
	}
	return 0
}

var File_s2_cs_gameevents_proto protoreflect.FileDescriptor

const file_s2_cs_gameevents_proto_rawDesc = "" +
	"\n" +
	"\x16s2/cs_gameevents.proto\x12)com.github.markus_wa.demoinfocs_golang.s2\x1a\x19s2/networkbasetypes.proto\"c\n" +
	"\x15CMsgTEPlayerAnimEvent\x12 \n" +
	"\x06player\x18\x01 \x01(\a:\b16777215R\x06player\x12\x14\n" +
	"\x05event\x18\x02 \x01(\rR\x05event\x12\x12\n" +
	"\x04data\x18\x03 \x01(\x05R\x04data\"3\n" +
	"\x0fCMsgTERadioIcon\x12 \n" +
	"\x06player\x18\x01 \x01(\a:\b16777215R\x06player\"\x97\x05\n" +
	"\x11CMsgTEFireBullets\x12M\n" +
	"\x06origin\x18\x01 \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgVectorR\x06origin\x12M\n" +
	"\x06angles\x18\x02 \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngleR\x06angles\x12%\n" +
	"\tweapon_id\x18\x03 \x01(\r:\b16777215R\bweaponId\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\rR\x04seed\x12 \n" +
	"\x06player\x18\x06 \x01(\a:\b16777215R\x06player\x12\x1e\n" +
	"\n" +
	"inaccuracy\x18\a \x01(\x02R\n" +
	"inaccuracy\x12!\n" +
	"\frecoil_index\x18\b \x01(\x02R\vrecoilIndex\x12\x16\n" +
	"\x06spread\x18\t \x01(\x02R\x06spread\x12\x1d\n" +
	"\n" +
	"sound_type\x18\n" +
	" \x01(\x05R\tsoundType\x12$\n" +
	"\x0eitem_def_index\x18\v \x01(\rR\fitemDefIndex\x12(\n" +
	"\x10sound_dsp_effect\x18\f \x01(\aR\x0esoundDspEffect\x12T\n" +
	"\n" +
	"ent_origin\x18\r \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgVectorR\tentOrigin\x122\n" +
	"\x15num_bullets_remaining\x18\x0e \x01(\rR\x13numBulletsRemaining\x12\x1f\n" +
	"\vattack_type\x18\x0f \x01(\rR\n" +
	"attackType*]\n" +
	"\x0fECsgoGameEvents\x12\x19\n" +
	"\x14GE_PlayerAnimEventId\x10\xc2\x03\x12\x18\n" +
	"\x13GE_RadioIconEventId\x10\xc3\x03\x12\x15\n" +
	"\x10GE_FireBulletsId\x10\xc4\x03"

var (
	file_s2_cs_gameevents_proto_rawDescOnce sync.Once
	file_s2_cs_gameevents_proto_rawDescData []byte
)

func file_s2_cs_gameevents_proto_rawDescGZIP() []byte {
	file_s2_cs_gameevents_proto_rawDescOnce.Do(func() {
		file_s2_cs_gameevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2_cs_gameevents_proto_rawDesc), len(file_s2_cs_gameevents_proto_rawDesc)))
	})
	return file_s2_cs_gameevents_proto_rawDescData
}

var file_s2_cs_gameevents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_s2_cs_gameevents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_s2_cs_gameevents_proto_goTypes = []any{
	(ECsgoGameEvents)(0),          // 0: com.github.markus_wa.demoinfocs_golang.s2.ECsgoGameEvents
	(*CMsgTEPlayerAnimEvent)(nil), // 1: com.github.markus_wa.demoinfocs_golang.s2.CMsgTEPlayerAnimEvent
	(*CMsgTERadioIcon)(nil),       // 2: com.github.markus_wa.demoinfocs_golang.s2.CMsgTERadioIcon
	(*CMsgTEFireBullets)(nil),     // 3: com.github.markus_wa.demoinfocs_golang.s2.CMsgTEFireBullets
	(*CMsgVector)(nil),            // 4: com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	(*CMsgQAngle)(nil),            // 5: com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngle
}
var file_s2_cs_gameevents_proto_depIdxs = []int32{
	4, // 0: com.github.markus_wa.demoinfocs_golang.s2.CMsgTEFireBullets.origin:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	5, // 1: com.github.markus_wa.demoinfocs_golang.s2.CMsgTEFireBullets.angles:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngle
	4, // 2: com.github.markus_wa.demoinfocs_golang.s2.CMsgTEFireBullets.ent_origin:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_s2_cs_gameevents_proto_init() }
func file_s2_cs_gameevents_proto_init() {
	if File_s2_cs_gameevents_proto != nil {
		return
	}
	file_s2_networkbasetypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2_cs_gameevents_proto_rawDesc), len(file_s2_cs_gameevents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2_cs_gameevents_proto_goTypes,
		DependencyIndexes: file_s2_cs_gameevents_proto_depIdxs,
		EnumInfos:         file_s2_cs_gameevents_proto_enumTypes,
		MessageInfos:      file_s2_cs_gameevents_proto_msgTypes,
	}.Build()
	File_s2_cs_gameevents_proto = out.File
	file_s2_cs_gameevents_proto_goTypes = nil
	file_s2_cs_gameevents_proto_depIdxs = nil
}
