// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: s2/cs_usercmd.proto

package msgs2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSGOInterpolationInfoPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcTick       *int32                 `protobuf:"varint,1,opt,name=src_tick,json=srcTick,def=-1" json:"src_tick,omitempty"`
	DstTick       *int32                 `protobuf:"varint,2,opt,name=dst_tick,json=dstTick,def=-1" json:"dst_tick,omitempty"`
	Frac          *float32               `protobuf:"fixed32,3,opt,name=frac,def=0" json:"frac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CSGOInterpolationInfoPB fields.
const (
	Default_CSGOInterpolationInfoPB_SrcTick = int32(-1)
	Default_CSGOInterpolationInfoPB_DstTick = int32(-1)
	Default_CSGOInterpolationInfoPB_Frac    = float32(0)
)

func (x *CSGOInterpolationInfoPB) Reset() {
	*x = CSGOInterpolationInfoPB{}
	mi := &file_s2_cs_usercmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSGOInterpolationInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGOInterpolationInfoPB) ProtoMessage() {}

func (x *CSGOInterpolationInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_usercmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGOInterpolationInfoPB.ProtoReflect.Descriptor instead.
func (*CSGOInterpolationInfoPB) Descriptor() ([]byte, []int) {
	return file_s2_cs_usercmd_proto_rawDescGZIP(), []int{0}
}

func (x *CSGOInterpolationInfoPB) GetSrcTick() int32 {
	if x != nil && x.SrcTick != nil {
		return *x.SrcTick
	}
	return Default_CSGOInterpolationInfoPB_SrcTick
}

func (x *CSGOInterpolationInfoPB) GetDstTick() int32 {
	if x != nil && x.DstTick != nil {
		return *x.DstTick
	}
	return Default_CSGOInterpolationInfoPB_DstTick
}

func (x *CSGOInterpolationInfoPB) GetFrac() float32 {
	if x != nil && x.Frac != nil {
		return *x.Frac
	}
	return Default_CSGOInterpolationInfoPB_Frac
}

type CSGOInterpolationInfoPB_CL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frac          *float32               `protobuf:"fixed32,3,opt,name=frac,def=0" json:"frac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CSGOInterpolationInfoPB_CL fields.
const (
	Default_CSGOInterpolationInfoPB_CL_Frac = float32(0)
)

func (x *CSGOInterpolationInfoPB_CL) Reset() {
	*x = CSGOInterpolationInfoPB_CL{}
	mi := &file_s2_cs_usercmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSGOInterpolationInfoPB_CL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGOInterpolationInfoPB_CL) ProtoMessage() {}

func (x *CSGOInterpolationInfoPB_CL) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_usercmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGOInterpolationInfoPB_CL.ProtoReflect.Descriptor instead.
func (*CSGOInterpolationInfoPB_CL) Descriptor() ([]byte, []int) {
	return file_s2_cs_usercmd_proto_rawDescGZIP(), []int{1}
}

func (x *CSGOInterpolationInfoPB_CL) GetFrac() float32 {
	if x != nil && x.Frac != nil {
		return *x.Frac
	}
	return Default_CSGOInterpolationInfoPB_CL_Frac
}

type CSGOInputHistoryEntryPB struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	ViewAngles         *CMsgQAngle                 `protobuf:"bytes,2,opt,name=view_angles,json=viewAngles" json:"view_angles,omitempty"`
	RenderTickCount    *int32                      `protobuf:"varint,4,opt,name=render_tick_count,json=renderTickCount" json:"render_tick_count,omitempty"`
	RenderTickFraction *float32                    `protobuf:"fixed32,5,opt,name=render_tick_fraction,json=renderTickFraction" json:"render_tick_fraction,omitempty"`
	PlayerTickCount    *int32                      `protobuf:"varint,6,opt,name=player_tick_count,json=playerTickCount" json:"player_tick_count,omitempty"`
	PlayerTickFraction *float32                    `protobuf:"fixed32,7,opt,name=player_tick_fraction,json=playerTickFraction" json:"player_tick_fraction,omitempty"`
	ClInterp           *CSGOInterpolationInfoPB_CL `protobuf:"bytes,12,opt,name=cl_interp,json=clInterp" json:"cl_interp,omitempty"`
	SvInterp0          *CSGOInterpolationInfoPB    `protobuf:"bytes,13,opt,name=sv_interp0,json=svInterp0" json:"sv_interp0,omitempty"`
	SvInterp1          *CSGOInterpolationInfoPB    `protobuf:"bytes,14,opt,name=sv_interp1,json=svInterp1" json:"sv_interp1,omitempty"`
	PlayerInterp       *CSGOInterpolationInfoPB    `protobuf:"bytes,15,opt,name=player_interp,json=playerInterp" json:"player_interp,omitempty"`
	FrameNumber        *int32                      `protobuf:"varint,64,opt,name=frame_number,json=frameNumber" json:"frame_number,omitempty"`
	TargetEntIndex     *int32                      `protobuf:"varint,65,opt,name=target_ent_index,json=targetEntIndex,def=-1" json:"target_ent_index,omitempty"`
	ShootPosition      *CMsgVector                 `protobuf:"bytes,66,opt,name=shoot_position,json=shootPosition" json:"shoot_position,omitempty"`
	TargetHeadPosCheck *CMsgVector                 `protobuf:"bytes,67,opt,name=target_head_pos_check,json=targetHeadPosCheck" json:"target_head_pos_check,omitempty"`
	TargetAbsPosCheck  *CMsgVector                 `protobuf:"bytes,68,opt,name=target_abs_pos_check,json=targetAbsPosCheck" json:"target_abs_pos_check,omitempty"`
	TargetAbsAngCheck  *CMsgQAngle                 `protobuf:"bytes,69,opt,name=target_abs_ang_check,json=targetAbsAngCheck" json:"target_abs_ang_check,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CSGOInputHistoryEntryPB fields.
const (
	Default_CSGOInputHistoryEntryPB_TargetEntIndex = int32(-1)
)

func (x *CSGOInputHistoryEntryPB) Reset() {
	*x = CSGOInputHistoryEntryPB{}
	mi := &file_s2_cs_usercmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSGOInputHistoryEntryPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGOInputHistoryEntryPB) ProtoMessage() {}

func (x *CSGOInputHistoryEntryPB) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_usercmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGOInputHistoryEntryPB.ProtoReflect.Descriptor instead.
func (*CSGOInputHistoryEntryPB) Descriptor() ([]byte, []int) {
	return file_s2_cs_usercmd_proto_rawDescGZIP(), []int{2}
}

func (x *CSGOInputHistoryEntryPB) GetViewAngles() *CMsgQAngle {
	if x != nil {
		return x.ViewAngles
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetRenderTickCount() int32 {
	if x != nil && x.RenderTickCount != nil {
		return *x.RenderTickCount
	}
	return 0
}

func (x *CSGOInputHistoryEntryPB) GetRenderTickFraction() float32 {
	if x != nil && x.RenderTickFraction != nil {
		return *x.RenderTickFraction
	}
	return 0
}

func (x *CSGOInputHistoryEntryPB) GetPlayerTickCount() int32 {
	if x != nil && x.PlayerTickCount != nil {
		return *x.PlayerTickCount
	}
	return 0
}

func (x *CSGOInputHistoryEntryPB) GetPlayerTickFraction() float32 {
	if x != nil && x.PlayerTickFraction != nil {
		return *x.PlayerTickFraction
	}
	return 0
}

func (x *CSGOInputHistoryEntryPB) GetClInterp() *CSGOInterpolationInfoPB_CL {
	if x != nil {
		return x.ClInterp
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetSvInterp0() *CSGOInterpolationInfoPB {
	if x != nil {
		return x.SvInterp0
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetSvInterp1() *CSGOInterpolationInfoPB {
	if x != nil {
		return x.SvInterp1
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetPlayerInterp() *CSGOInterpolationInfoPB {
	if x != nil {
		return x.PlayerInterp
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetFrameNumber() int32 {
	if x != nil && x.FrameNumber != nil {
		return *x.FrameNumber
	}
	return 0
}

func (x *CSGOInputHistoryEntryPB) GetTargetEntIndex() int32 {
	if x != nil && x.TargetEntIndex != nil {
		return *x.TargetEntIndex
	}
	return Default_CSGOInputHistoryEntryPB_TargetEntIndex
}

func (x *CSGOInputHistoryEntryPB) GetShootPosition() *CMsgVector {
	if x != nil {
		return x.ShootPosition
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetTargetHeadPosCheck() *CMsgVector {
	if x != nil {
		return x.TargetHeadPosCheck
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetTargetAbsPosCheck() *CMsgVector {
	if x != nil {
		return x.TargetAbsPosCheck
	}
	return nil
}

func (x *CSGOInputHistoryEntryPB) GetTargetAbsAngCheck() *CMsgQAngle {
	if x != nil {
		return x.TargetAbsAngCheck
	}
	return nil
}

type CSGOUserCmdPB struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	Base                     *CBaseUserCmdPB            `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	InputHistory             []*CSGOInputHistoryEntryPB `protobuf:"bytes,2,rep,name=input_history,json=inputHistory" json:"input_history,omitempty"`
	Attack1StartHistoryIndex *int32                     `protobuf:"varint,6,opt,name=attack1_start_history_index,json=attack1StartHistoryIndex,def=-1" json:"attack1_start_history_index,omitempty"`
	Attack2StartHistoryIndex *int32                     `protobuf:"varint,7,opt,name=attack2_start_history_index,json=attack2StartHistoryIndex,def=-1" json:"attack2_start_history_index,omitempty"`
	LeftHandDesired          *bool                      `protobuf:"varint,9,opt,name=left_hand_desired,json=leftHandDesired,def=0" json:"left_hand_desired,omitempty"`
	IsPredictingBodyShotFx   *bool                      `protobuf:"varint,11,opt,name=is_predicting_body_shot_fx,json=isPredictingBodyShotFx,def=0" json:"is_predicting_body_shot_fx,omitempty"`
	IsPredictingHeadShotFx   *bool                      `protobuf:"varint,12,opt,name=is_predicting_head_shot_fx,json=isPredictingHeadShotFx,def=0" json:"is_predicting_head_shot_fx,omitempty"`
	IsPredictingKillRagdolls *bool                      `protobuf:"varint,13,opt,name=is_predicting_kill_ragdolls,json=isPredictingKillRagdolls,def=0" json:"is_predicting_kill_ragdolls,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

// Default values for CSGOUserCmdPB fields.
const (
	Default_CSGOUserCmdPB_Attack1StartHistoryIndex = int32(-1)
	Default_CSGOUserCmdPB_Attack2StartHistoryIndex = int32(-1)
	Default_CSGOUserCmdPB_LeftHandDesired          = bool(false)
	Default_CSGOUserCmdPB_IsPredictingBodyShotFx   = bool(false)
	Default_CSGOUserCmdPB_IsPredictingHeadShotFx   = bool(false)
	Default_CSGOUserCmdPB_IsPredictingKillRagdolls = bool(false)
)

func (x *CSGOUserCmdPB) Reset() {
	*x = CSGOUserCmdPB{}
	mi := &file_s2_cs_usercmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSGOUserCmdPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSGOUserCmdPB) ProtoMessage() {}

func (x *CSGOUserCmdPB) ProtoReflect() protoreflect.Message {
	mi := &file_s2_cs_usercmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSGOUserCmdPB.ProtoReflect.Descriptor instead.
func (*CSGOUserCmdPB) Descriptor() ([]byte, []int) {
	return file_s2_cs_usercmd_proto_rawDescGZIP(), []int{3}
}

func (x *CSGOUserCmdPB) GetBase() *CBaseUserCmdPB {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CSGOUserCmdPB) GetInputHistory() []*CSGOInputHistoryEntryPB {
	if x != nil {
		return x.InputHistory
	}
	return nil
}

func (x *CSGOUserCmdPB) GetAttack1StartHistoryIndex() int32 {
	if x != nil && x.Attack1StartHistoryIndex != nil {
		return *x.Attack1StartHistoryIndex
	}
	return Default_CSGOUserCmdPB_Attack1StartHistoryIndex
}

func (x *CSGOUserCmdPB) GetAttack2StartHistoryIndex() int32 {
	if x != nil && x.Attack2StartHistoryIndex != nil {
		return *x.Attack2StartHistoryIndex
	}
	return Default_CSGOUserCmdPB_Attack2StartHistoryIndex
}

func (x *CSGOUserCmdPB) GetLeftHandDesired() bool {
	if x != nil && x.LeftHandDesired != nil {
		return *x.LeftHandDesired
	}
	return Default_CSGOUserCmdPB_LeftHandDesired
}

func (x *CSGOUserCmdPB) GetIsPredictingBodyShotFx() bool {
	if x != nil && x.IsPredictingBodyShotFx != nil {
		return *x.IsPredictingBodyShotFx
	}
	return Default_CSGOUserCmdPB_IsPredictingBodyShotFx
}

func (x *CSGOUserCmdPB) GetIsPredictingHeadShotFx() bool {
	if x != nil && x.IsPredictingHeadShotFx != nil {
		return *x.IsPredictingHeadShotFx
	}
	return Default_CSGOUserCmdPB_IsPredictingHeadShotFx
}

func (x *CSGOUserCmdPB) GetIsPredictingKillRagdolls() bool {
	if x != nil && x.IsPredictingKillRagdolls != nil {
		return *x.IsPredictingKillRagdolls
	}
	return Default_CSGOUserCmdPB_IsPredictingKillRagdolls
}

var File_s2_cs_usercmd_proto protoreflect.FileDescriptor

const file_s2_cs_usercmd_proto_rawDesc = "" +
	"\n" +
	"\x13s2/cs_usercmd.proto\x12)com.github.markus_wa.demoinfocs_golang.s2\x1a\x18s2/valveextensions.proto\x1a\x19s2/networkbasetypes.proto\x1a\x10s2/usercmd.proto\"t\n" +
	"\x17CSGOInterpolationInfoPB\x12\x1d\n" +
	"\bsrc_tick\x18\x01 \x01(\x05:\x02-1R\asrcTick\x12\x1d\n" +
	"\bdst_tick\x18\x02 \x01(\x05:\x02-1R\adstTick\x12\x15\n" +
	"\x04frac\x18\x03 \x01(\x02:\x010R\x04frac:\x04\xc0\xe4\x1d\x01\"9\n" +
	"\x1aCSGOInterpolationInfoPB_CL\x12\x15\n" +
	"\x04frac\x18\x03 \x01(\x02:\x010R\x04frac:\x04\xc0\xe4\x1d\x01\"\xaf\t\n" +
	"\x17CSGOInputHistoryEntryPB\x12V\n" +
	"\vview_angles\x18\x02 \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngleR\n" +
	"viewAngles\x12*\n" +
	"\x11render_tick_count\x18\x04 \x01(\x05R\x0frenderTickCount\x120\n" +
	"\x14render_tick_fraction\x18\x05 \x01(\x02R\x12renderTickFraction\x12*\n" +
	"\x11player_tick_count\x18\x06 \x01(\x05R\x0fplayerTickCount\x120\n" +
	"\x14player_tick_fraction\x18\a \x01(\x02R\x12playerTickFraction\x12b\n" +
	"\tcl_interp\x18\f \x01(\v2E.com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB_CLR\bclInterp\x12a\n" +
	"\n" +
	"sv_interp0\x18\r \x01(\v2B.com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPBR\tsvInterp0\x12a\n" +
	"\n" +
	"sv_interp1\x18\x0e \x01(\v2B.com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPBR\tsvInterp1\x12g\n" +
	"\rplayer_interp\x18\x0f \x01(\v2B.com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPBR\fplayerInterp\x12!\n" +
	"\fframe_number\x18@ \x01(\x05R\vframeNumber\x12,\n" +
	"\x10target_ent_index\x18A \x01(\x05:\x02-1R\x0etargetEntIndex\x12\\\n" +
	"\x0eshoot_position\x18B \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgVectorR\rshootPosition\x12h\n" +
	"\x15target_head_pos_check\x18C \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgVectorR\x12targetHeadPosCheck\x12f\n" +
	"\x14target_abs_pos_check\x18D \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgVectorR\x11targetAbsPosCheck\x12f\n" +
	"\x14target_abs_ang_check\x18E \x01(\v25.com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngleR\x11targetAbsAngCheck:\x04\xc0\xe4\x1d\x01\"\xd2\x04\n" +
	"\rCSGOUserCmdPB\x12M\n" +
	"\x04base\x18\x01 \x01(\v29.com.github.markus_wa.demoinfocs_golang.s2.CBaseUserCmdPBR\x04base\x12g\n" +
	"\rinput_history\x18\x02 \x03(\v2B.com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPBR\finputHistory\x12A\n" +
	"\x1battack1_start_history_index\x18\x06 \x01(\x05:\x02-1R\x18attack1StartHistoryIndex\x12A\n" +
	"\x1battack2_start_history_index\x18\a \x01(\x05:\x02-1R\x18attack2StartHistoryIndex\x121\n" +
	"\x11left_hand_desired\x18\t \x01(\b:\x05falseR\x0fleftHandDesired\x12A\n" +
	"\x1ais_predicting_body_shot_fx\x18\v \x01(\b:\x05falseR\x16isPredictingBodyShotFx\x12A\n" +
	"\x1ais_predicting_head_shot_fx\x18\f \x01(\b:\x05falseR\x16isPredictingHeadShotFx\x12D\n" +
	"\x1bis_predicting_kill_ragdolls\x18\r \x01(\b:\x05falseR\x18isPredictingKillRagdolls:\x04\xc0\xe4\x1d\x01"

var (
	file_s2_cs_usercmd_proto_rawDescOnce sync.Once
	file_s2_cs_usercmd_proto_rawDescData []byte
)

func file_s2_cs_usercmd_proto_rawDescGZIP() []byte {
	file_s2_cs_usercmd_proto_rawDescOnce.Do(func() {
		file_s2_cs_usercmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2_cs_usercmd_proto_rawDesc), len(file_s2_cs_usercmd_proto_rawDesc)))
	})
	return file_s2_cs_usercmd_proto_rawDescData
}

var file_s2_cs_usercmd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_s2_cs_usercmd_proto_goTypes = []any{
	(*CSGOInterpolationInfoPB)(nil),    // 0: com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB
	(*CSGOInterpolationInfoPB_CL)(nil), // 1: com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB_CL
	(*CSGOInputHistoryEntryPB)(nil),    // 2: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB
	(*CSGOUserCmdPB)(nil),              // 3: com.github.markus_wa.demoinfocs_golang.s2.CSGOUserCmdPB
	(*CMsgQAngle)(nil),                 // 4: com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngle
	(*CMsgVector)(nil),                 // 5: com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	(*CBaseUserCmdPB)(nil),             // 6: com.github.markus_wa.demoinfocs_golang.s2.CBaseUserCmdPB
}
var file_s2_cs_usercmd_proto_depIdxs = []int32{
	4,  // 0: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.view_angles:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngle
	1,  // 1: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.cl_interp:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB_CL
	0,  // 2: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.sv_interp0:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB
	0,  // 3: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.sv_interp1:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB
	0,  // 4: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.player_interp:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CSGOInterpolationInfoPB
	5,  // 5: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.shoot_position:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	5,  // 6: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.target_head_pos_check:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	5,  // 7: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.target_abs_pos_check:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgVector
	4,  // 8: com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB.target_abs_ang_check:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CMsgQAngle
	6,  // 9: com.github.markus_wa.demoinfocs_golang.s2.CSGOUserCmdPB.base:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CBaseUserCmdPB
	2,  // 10: com.github.markus_wa.demoinfocs_golang.s2.CSGOUserCmdPB.input_history:type_name -> com.github.markus_wa.demoinfocs_golang.s2.CSGOInputHistoryEntryPB
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_s2_cs_usercmd_proto_init() }
func file_s2_cs_usercmd_proto_init() {
	if File_s2_cs_usercmd_proto != nil {
		return
	}
	file_s2_valveextensions_proto_init()
	file_s2_networkbasetypes_proto_init()
	file_s2_usercmd_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2_cs_usercmd_proto_rawDesc), len(file_s2_cs_usercmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s2_cs_usercmd_proto_goTypes,
		DependencyIndexes: file_s2_cs_usercmd_proto_depIdxs,
		MessageInfos:      file_s2_cs_usercmd_proto_msgTypes,
	}.Build()
	File_s2_cs_usercmd_proto = out.File
	file_s2_cs_usercmd_proto_goTypes = nil
	file_s2_cs_usercmd_proto_depIdxs = nil
}
