// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: s2/steammessages.proto

package msgs2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GCProtoBufMsgSrc int32

const (
	GCProtoBufMsgSrc_GCProtoBufMsgSrc_Unspecified GCProtoBufMsgSrc = 0
	GCProtoBufMsgSrc_GCProtoBufMsgSrc_FromSystem  GCProtoBufMsgSrc = 1
	GCProtoBufMsgSrc_GCProtoBufMsgSrc_FromSteamID GCProtoBufMsgSrc = 2
	GCProtoBufMsgSrc_GCProtoBufMsgSrc_FromGC      GCProtoBufMsgSrc = 3
	GCProtoBufMsgSrc_GCProtoBufMsgSrc_ReplySystem GCProtoBufMsgSrc = 4
)

// Enum value maps for GCProtoBufMsgSrc.
var (
	GCProtoBufMsgSrc_name = map[int32]string{
		0: "GCProtoBufMsgSrc_Unspecified",
		1: "GCProtoBufMsgSrc_FromSystem",
		2: "GCProtoBufMsgSrc_FromSteamID",
		3: "GCProtoBufMsgSrc_FromGC",
		4: "GCProtoBufMsgSrc_ReplySystem",
	}
	GCProtoBufMsgSrc_value = map[string]int32{
		"GCProtoBufMsgSrc_Unspecified": 0,
		"GCProtoBufMsgSrc_FromSystem":  1,
		"GCProtoBufMsgSrc_FromSteamID": 2,
		"GCProtoBufMsgSrc_FromGC":      3,
		"GCProtoBufMsgSrc_ReplySystem": 4,
	}
)

func (x GCProtoBufMsgSrc) Enum() *GCProtoBufMsgSrc {
	p := new(GCProtoBufMsgSrc)
	*p = x
	return p
}

func (x GCProtoBufMsgSrc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GCProtoBufMsgSrc) Descriptor() protoreflect.EnumDescriptor {
	return file_s2_steammessages_proto_enumTypes[0].Descriptor()
}

func (GCProtoBufMsgSrc) Type() protoreflect.EnumType {
	return &file_s2_steammessages_proto_enumTypes[0]
}

func (x GCProtoBufMsgSrc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GCProtoBufMsgSrc) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GCProtoBufMsgSrc(num)
	return nil
}

// Deprecated: Use GCProtoBufMsgSrc.Descriptor instead.
func (GCProtoBufMsgSrc) EnumDescriptor() ([]byte, []int) {
	return file_s2_steammessages_proto_rawDescGZIP(), []int{0}
}

type CMsgProtoBufHeader struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientSteamId    *uint64                `protobuf:"fixed64,1,opt,name=client_steam_id,json=clientSteamId" json:"client_steam_id,omitempty"`
	ClientSessionId  *int32                 `protobuf:"varint,2,opt,name=client_session_id,json=clientSessionId" json:"client_session_id,omitempty"`
	SourceAppId      *uint32                `protobuf:"varint,3,opt,name=source_app_id,json=sourceAppId" json:"source_app_id,omitempty"`
	JobIdSource      *uint64                `protobuf:"fixed64,10,opt,name=job_id_source,json=jobIdSource,def=18446744073709551615" json:"job_id_source,omitempty"`
	JobIdTarget      *uint64                `protobuf:"fixed64,11,opt,name=job_id_target,json=jobIdTarget,def=18446744073709551615" json:"job_id_target,omitempty"`
	TargetJobName    *string                `protobuf:"bytes,12,opt,name=target_job_name,json=targetJobName" json:"target_job_name,omitempty"`
	Eresult          *int32                 `protobuf:"varint,13,opt,name=eresult,def=2" json:"eresult,omitempty"`
	ErrorMessage     *string                `protobuf:"bytes,14,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	Ip               *uint32                `protobuf:"varint,15,opt,name=ip" json:"ip,omitempty"`
	GcMsgSrc         *GCProtoBufMsgSrc      `protobuf:"varint,200,opt,name=gc_msg_src,json=gcMsgSrc,enum=com.github.markus_wa.demoinfocs_golang.s2.GCProtoBufMsgSrc,def=0" json:"gc_msg_src,omitempty"`
	GcDirIndexSource *uint32                `protobuf:"varint,201,opt,name=gc_dir_index_source,json=gcDirIndexSource" json:"gc_dir_index_source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

// Default values for CMsgProtoBufHeader fields.
const (
	Default_CMsgProtoBufHeader_JobIdSource = uint64(18446744073709551615)
	Default_CMsgProtoBufHeader_JobIdTarget = uint64(18446744073709551615)
	Default_CMsgProtoBufHeader_Eresult     = int32(2)
	Default_CMsgProtoBufHeader_GcMsgSrc    = GCProtoBufMsgSrc_GCProtoBufMsgSrc_Unspecified
)

func (x *CMsgProtoBufHeader) Reset() {
	*x = CMsgProtoBufHeader{}
	mi := &file_s2_steammessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgProtoBufHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgProtoBufHeader) ProtoMessage() {}

func (x *CMsgProtoBufHeader) ProtoReflect() protoreflect.Message {
	mi := &file_s2_steammessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgProtoBufHeader.ProtoReflect.Descriptor instead.
func (*CMsgProtoBufHeader) Descriptor() ([]byte, []int) {
	return file_s2_steammessages_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgProtoBufHeader) GetClientSteamId() uint64 {
	if x != nil && x.ClientSteamId != nil {
		return *x.ClientSteamId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetClientSessionId() int32 {
	if x != nil && x.ClientSessionId != nil {
		return *x.ClientSessionId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetSourceAppId() uint32 {
	if x != nil && x.SourceAppId != nil {
		return *x.SourceAppId
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetJobIdSource() uint64 {
	if x != nil && x.JobIdSource != nil {
		return *x.JobIdSource
	}
	return Default_CMsgProtoBufHeader_JobIdSource
}

func (x *CMsgProtoBufHeader) GetJobIdTarget() uint64 {
	if x != nil && x.JobIdTarget != nil {
		return *x.JobIdTarget
	}
	return Default_CMsgProtoBufHeader_JobIdTarget
}

func (x *CMsgProtoBufHeader) GetTargetJobName() string {
	if x != nil && x.TargetJobName != nil {
		return *x.TargetJobName
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetEresult() int32 {
	if x != nil && x.Eresult != nil {
		return *x.Eresult
	}
	return Default_CMsgProtoBufHeader_Eresult
}

func (x *CMsgProtoBufHeader) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *CMsgProtoBufHeader) GetIp() uint32 {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return 0
}

func (x *CMsgProtoBufHeader) GetGcMsgSrc() GCProtoBufMsgSrc {
	if x != nil && x.GcMsgSrc != nil {
		return *x.GcMsgSrc
	}
	return Default_CMsgProtoBufHeader_GcMsgSrc
}

func (x *CMsgProtoBufHeader) GetGcDirIndexSource() uint32 {
	if x != nil && x.GcDirIndexSource != nil {
		return *x.GcDirIndexSource
	}
	return 0
}

type CChinaAgreementSessions_StartAgreementSessionInGame_Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Appid           *uint32                `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid         *uint64                `protobuf:"fixed64,2,opt,name=steamid" json:"steamid,omitempty"`
	ClientIpaddress *string                `protobuf:"bytes,3,opt,name=client_ipaddress,json=clientIpaddress" json:"client_ipaddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) Reset() {
	*x = CChinaAgreementSessions_StartAgreementSessionInGame_Request{}
	mi := &file_s2_steammessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CChinaAgreementSessions_StartAgreementSessionInGame_Request) ProtoMessage() {}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) ProtoReflect() protoreflect.Message {
	mi := &file_s2_steammessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CChinaAgreementSessions_StartAgreementSessionInGame_Request.ProtoReflect.Descriptor instead.
func (*CChinaAgreementSessions_StartAgreementSessionInGame_Request) Descriptor() ([]byte, []int) {
	return file_s2_steammessages_proto_rawDescGZIP(), []int{1}
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Request) GetClientIpaddress() string {
	if x != nil && x.ClientIpaddress != nil {
		return *x.ClientIpaddress
	}
	return ""
}

type CChinaAgreementSessions_StartAgreementSessionInGame_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgreementUrl  *string                `protobuf:"bytes,1,opt,name=agreement_url,json=agreementUrl" json:"agreement_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Response) Reset() {
	*x = CChinaAgreementSessions_StartAgreementSessionInGame_Response{}
	mi := &file_s2_steammessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CChinaAgreementSessions_StartAgreementSessionInGame_Response) ProtoMessage() {}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Response) ProtoReflect() protoreflect.Message {
	mi := &file_s2_steammessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CChinaAgreementSessions_StartAgreementSessionInGame_Response.ProtoReflect.Descriptor instead.
func (*CChinaAgreementSessions_StartAgreementSessionInGame_Response) Descriptor() ([]byte, []int) {
	return file_s2_steammessages_proto_rawDescGZIP(), []int{2}
}

func (x *CChinaAgreementSessions_StartAgreementSessionInGame_Response) GetAgreementUrl() string {
	if x != nil && x.AgreementUrl != nil {
		return *x.AgreementUrl
	}
	return ""
}

var file_s2_steammessages_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         70000,
		Name:          "com.github.markus_wa.demoinfocs_golang.s2.key_field",
		Tag:           "varint,70000,opt,name=key_field,def=0",
		Filename:      "s2/steammessages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         70000,
		Name:          "com.github.markus_wa.demoinfocs_golang.s2.msgpool_soft_limit",
		Tag:           "varint,70000,opt,name=msgpool_soft_limit,def=32",
		Filename:      "s2/steammessages.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         70001,
		Name:          "com.github.markus_wa.demoinfocs_golang.s2.msgpool_hard_limit",
		Tag:           "varint,70001,opt,name=msgpool_hard_limit,def=384",
		Filename:      "s2/steammessages.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool key_field = 70000;
	E_KeyField = &file_s2_steammessages_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional int32 msgpool_soft_limit = 70000;
	E_MsgpoolSoftLimit = &file_s2_steammessages_proto_extTypes[1]
	// optional int32 msgpool_hard_limit = 70001;
	E_MsgpoolHardLimit = &file_s2_steammessages_proto_extTypes[2]
)

var File_s2_steammessages_proto protoreflect.FileDescriptor

const file_s2_steammessages_proto_rawDesc = "" +
	"\n" +
	"\x16s2/steammessages.proto\x12)com.github.markus_wa.demoinfocs_golang.s2\x1a google/protobuf/descriptor.proto\"\xb0\x04\n" +
	"\x12CMsgProtoBufHeader\x12&\n" +
	"\x0fclient_steam_id\x18\x01 \x01(\x06R\rclientSteamId\x12*\n" +
	"\x11client_session_id\x18\x02 \x01(\x05R\x0fclientSessionId\x12\"\n" +
	"\rsource_app_id\x18\x03 \x01(\rR\vsourceAppId\x128\n" +
	"\rjob_id_source\x18\n" +
	" \x01(\x06:\x1418446744073709551615R\vjobIdSource\x128\n" +
	"\rjob_id_target\x18\v \x01(\x06:\x1418446744073709551615R\vjobIdTarget\x12&\n" +
	"\x0ftarget_job_name\x18\f \x01(\tR\rtargetJobName\x12\x1b\n" +
	"\aeresult\x18\r \x01(\x05:\x012R\aeresult\x12#\n" +
	"\rerror_message\x18\x0e \x01(\tR\ferrorMessage\x12\x0e\n" +
	"\x02ip\x18\x0f \x01(\rR\x02ip\x12x\n" +
	"\n" +
	"gc_msg_src\x18\xc8\x01 \x01(\x0e2;.com.github.markus_wa.demoinfocs_golang.s2.GCProtoBufMsgSrc:\x1cGCProtoBufMsgSrc_UnspecifiedR\bgcMsgSrc\x12.\n" +
	"\x13gc_dir_index_source\x18\xc9\x01 \x01(\rR\x10gcDirIndexSource:\n" +
	"\x80\x97\"\x80\x02\x88\x97\"\x80\b\"\x98\x01\n" +
	";CChinaAgreementSessions_StartAgreementSessionInGame_Request\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x18\n" +
	"\asteamid\x18\x02 \x01(\x06R\asteamid\x12)\n" +
	"\x10client_ipaddress\x18\x03 \x01(\tR\x0fclientIpaddress\"c\n" +
	"<CChinaAgreementSessions_StartAgreementSessionInGame_Response\x12#\n" +
	"\ragreement_url\x18\x01 \x01(\tR\fagreementUrl*\xb6\x01\n" +
	"\x10GCProtoBufMsgSrc\x12 \n" +
	"\x1cGCProtoBufMsgSrc_Unspecified\x10\x00\x12\x1f\n" +
	"\x1bGCProtoBufMsgSrc_FromSystem\x10\x01\x12 \n" +
	"\x1cGCProtoBufMsgSrc_FromSteamID\x10\x02\x12\x1b\n" +
	"\x17GCProtoBufMsgSrc_FromGC\x10\x03\x12 \n" +
	"\x1cGCProtoBufMsgSrc_ReplySystem\x10\x04:C\n" +
	"\tkey_field\x12\x1d.google.protobuf.FieldOptions\x18\xf0\xa2\x04 \x01(\b:\x05falseR\bkeyField:S\n" +
	"\x12msgpool_soft_limit\x12\x1f.google.protobuf.MessageOptions\x18\xf0\xa2\x04 \x01(\x05:\x0232R\x10msgpoolSoftLimit:T\n" +
	"\x12msgpool_hard_limit\x12\x1f.google.protobuf.MessageOptions\x18\xf1\xa2\x04 \x01(\x05:\x03384R\x10msgpoolHardLimit"

var (
	file_s2_steammessages_proto_rawDescOnce sync.Once
	file_s2_steammessages_proto_rawDescData []byte
)

func file_s2_steammessages_proto_rawDescGZIP() []byte {
	file_s2_steammessages_proto_rawDescOnce.Do(func() {
		file_s2_steammessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s2_steammessages_proto_rawDesc), len(file_s2_steammessages_proto_rawDesc)))
	})
	return file_s2_steammessages_proto_rawDescData
}

var file_s2_steammessages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_s2_steammessages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_s2_steammessages_proto_goTypes = []any{
	(GCProtoBufMsgSrc)(0),      // 0: com.github.markus_wa.demoinfocs_golang.s2.GCProtoBufMsgSrc
	(*CMsgProtoBufHeader)(nil), // 1: com.github.markus_wa.demoinfocs_golang.s2.CMsgProtoBufHeader
	(*CChinaAgreementSessions_StartAgreementSessionInGame_Request)(nil),  // 2: com.github.markus_wa.demoinfocs_golang.s2.CChinaAgreementSessions_StartAgreementSessionInGame_Request
	(*CChinaAgreementSessions_StartAgreementSessionInGame_Response)(nil), // 3: com.github.markus_wa.demoinfocs_golang.s2.CChinaAgreementSessions_StartAgreementSessionInGame_Response
	(*descriptorpb.FieldOptions)(nil),                                    // 4: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil),                                  // 5: google.protobuf.MessageOptions
}
var file_s2_steammessages_proto_depIdxs = []int32{
	0, // 0: com.github.markus_wa.demoinfocs_golang.s2.CMsgProtoBufHeader.gc_msg_src:type_name -> com.github.markus_wa.demoinfocs_golang.s2.GCProtoBufMsgSrc
	4, // 1: com.github.markus_wa.demoinfocs_golang.s2.key_field:extendee -> google.protobuf.FieldOptions
	5, // 2: com.github.markus_wa.demoinfocs_golang.s2.msgpool_soft_limit:extendee -> google.protobuf.MessageOptions
	5, // 3: com.github.markus_wa.demoinfocs_golang.s2.msgpool_hard_limit:extendee -> google.protobuf.MessageOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	1, // [1:4] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_s2_steammessages_proto_init() }
func file_s2_steammessages_proto_init() {
	if File_s2_steammessages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s2_steammessages_proto_rawDesc), len(file_s2_steammessages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_s2_steammessages_proto_goTypes,
		DependencyIndexes: file_s2_steammessages_proto_depIdxs,
		EnumInfos:         file_s2_steammessages_proto_enumTypes,
		MessageInfos:      file_s2_steammessages_proto_msgTypes,
		ExtensionInfos:    file_s2_steammessages_proto_extTypes,
	}.Build()
	File_s2_steammessages_proto = out.File
	file_s2_steammessages_proto_goTypes = nil
	file_s2_steammessages_proto_depIdxs = nil
}
