// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: engine_gcmessages.proto

package msg

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CEngineGotvSyncPacket struct {
	MatchId          uint64  `protobuf:"varint,1,opt,name=match_id,json=matchId" json:"match_id"`
	InstanceId       uint32  `protobuf:"varint,2,opt,name=instance_id,json=instanceId" json:"instance_id"`
	Signupfragment   uint32  `protobuf:"varint,3,opt,name=signupfragment" json:"signupfragment"`
	Currentfragment  uint32  `protobuf:"varint,4,opt,name=currentfragment" json:"currentfragment"`
	Tickrate         float32 `protobuf:"fixed32,5,opt,name=tickrate" json:"tickrate"`
	Tick             uint32  `protobuf:"varint,6,opt,name=tick" json:"tick"`
	Rtdelay          float32 `protobuf:"fixed32,8,opt,name=rtdelay" json:"rtdelay"`
	Rcvage           float32 `protobuf:"fixed32,9,opt,name=rcvage" json:"rcvage"`
	KeyframeInterval float32 `protobuf:"fixed32,10,opt,name=keyframe_interval,json=keyframeInterval" json:"keyframe_interval"`
}

func (m *CEngineGotvSyncPacket) Reset()         { *m = CEngineGotvSyncPacket{} }
func (m *CEngineGotvSyncPacket) String() string { return proto.CompactTextString(m) }
func (*CEngineGotvSyncPacket) ProtoMessage()    {}
func (*CEngineGotvSyncPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_32a42573523bc825, []int{0}
}
func (m *CEngineGotvSyncPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CEngineGotvSyncPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CEngineGotvSyncPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CEngineGotvSyncPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CEngineGotvSyncPacket.Merge(m, src)
}
func (m *CEngineGotvSyncPacket) XXX_Size() int {
	return m.Size()
}
func (m *CEngineGotvSyncPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_CEngineGotvSyncPacket.DiscardUnknown(m)
}

var xxx_messageInfo_CEngineGotvSyncPacket proto.InternalMessageInfo

func (m *CEngineGotvSyncPacket) GetMatchId() uint64 {
	if m != nil {
		return m.MatchId
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetInstanceId() uint32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetSignupfragment() uint32 {
	if m != nil {
		return m.Signupfragment
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetCurrentfragment() uint32 {
	if m != nil {
		return m.Currentfragment
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetTickrate() float32 {
	if m != nil {
		return m.Tickrate
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetTick() uint32 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetRtdelay() float32 {
	if m != nil {
		return m.Rtdelay
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetRcvage() float32 {
	if m != nil {
		return m.Rcvage
	}
	return 0
}

func (m *CEngineGotvSyncPacket) GetKeyframeInterval() float32 {
	if m != nil {
		return m.KeyframeInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*CEngineGotvSyncPacket)(nil), "CEngineGotvSyncPacket")
}

func init() { proto.RegisterFile("engine_gcmessages.proto", fileDescriptor_32a42573523bc825) }

var fileDescriptor_32a42573523bc825 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8c, 0xcf, 0x4a, 0x33, 0x31,
	0x14, 0x47, 0x27, 0xed, 0x7c, 0x6d, 0xbf, 0x2b, 0xfe, 0x0b, 0x88, 0x41, 0x24, 0x1d, 0x04, 0xa1,
	0x0b, 0x69, 0xf1, 0x15, 0x2a, 0x22, 0xdd, 0x89, 0xee, 0xdc, 0x94, 0x98, 0xb9, 0x8d, 0xa1, 0x9d,
	0x4c, 0x49, 0xd2, 0x42, 0x77, 0x3e, 0x82, 0x8f, 0xd5, 0x65, 0x97, 0xae, 0x44, 0xda, 0x9d, 0x4f,
	0x21, 0x1d, 0x67, 0x4a, 0xe8, 0x2e, 0x39, 0xe7, 0xfc, 0x2e, 0x9c, 0xa3, 0x51, 0xda, 0xe0, 0x50,
	0xc9, 0x0c, 0x9d, 0x13, 0x0a, 0x5d, 0x77, 0x6a, 0x73, 0x9f, 0x5f, 0x24, 0x2a, 0xcf, 0xd5, 0x04,
	0x7b, 0xc5, 0xef, 0x75, 0x36, 0xea, 0xa5, 0xe8, 0xa4, 0xd5, 0x53, 0x9f, 0xdb, 0xbf, 0xe2, 0xea,
	0xa7, 0x06, 0x67, 0x77, 0xf7, 0xc5, 0xfc, 0x21, 0xf7, 0xf3, 0xe7, 0x85, 0x91, 0x8f, 0x42, 0x8e,
	0xd1, 0xd3, 0x36, 0xb4, 0x32, 0xe1, 0xe5, 0xdb, 0x50, 0xa7, 0x8c, 0x24, 0xa4, 0x13, 0xf7, 0xe3,
	0xe5, 0x57, 0x3b, 0x7a, 0x6a, 0x16, 0x74, 0x90, 0xd2, 0x6b, 0x38, 0xd0, 0xc6, 0x79, 0x61, 0x24,
	0x6e, 0x9b, 0x5a, 0x42, 0x3a, 0x87, 0x65, 0x03, 0x95, 0x18, 0xa4, 0xf4, 0x06, 0x8e, 0x9c, 0x56,
	0x66, 0x36, 0x1d, 0x59, 0xa1, 0x32, 0x34, 0x9e, 0xd5, 0x83, 0x72, 0xcf, 0xd1, 0x2e, 0x1c, 0xcb,
	0x99, 0xb5, 0x68, 0xfc, 0x2e, 0x8f, 0x83, 0x7c, 0x5f, 0xd2, 0x04, 0x5a, 0x5e, 0xcb, 0xb1, 0x15,
	0x1e, 0xd9, 0xbf, 0x84, 0x74, 0x6a, 0x65, 0xb8, 0xa3, 0x94, 0x41, 0xbc, 0x7d, 0xb3, 0x46, 0x70,
	0xa6, 0x20, 0x94, 0x43, 0xd3, 0xfa, 0x14, 0x27, 0x62, 0xc1, 0x5a, 0xc1, 0xb4, 0x82, 0xf4, 0x12,
	0x1a, 0x56, 0xce, 0x85, 0x42, 0xf6, 0x3f, 0xd0, 0x25, 0xa3, 0xb7, 0x70, 0x3a, 0xc6, 0xc5, 0xc8,
	0x8a, 0x0c, 0x87, 0xda, 0x78, 0xb4, 0x73, 0x31, 0x61, 0x10, 0x84, 0x27, 0x95, 0x1e, 0x94, 0xb6,
	0x9f, 0x2c, 0xd7, 0x9c, 0xac, 0xd6, 0x9c, 0x7c, 0xaf, 0x39, 0xf9, 0xd8, 0xf0, 0x68, 0xb5, 0xe1,
	0xd1, 0xe7, 0x86, 0x47, 0x2f, 0xf5, 0xcc, 0xa9, 0x77, 0x12, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xef, 0x47, 0x2d, 0xca, 0x01, 0x00, 0x00,
}

func (m *CEngineGotvSyncPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CEngineGotvSyncPacket) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	i = encodeVarintEngineGcmessages(dAtA, i, uint64(m.MatchId))
	dAtA[i] = 0x10
	i++
	i = encodeVarintEngineGcmessages(dAtA, i, uint64(m.InstanceId))
	dAtA[i] = 0x18
	i++
	i = encodeVarintEngineGcmessages(dAtA, i, uint64(m.Signupfragment))
	dAtA[i] = 0x20
	i++
	i = encodeVarintEngineGcmessages(dAtA, i, uint64(m.Currentfragment))
	dAtA[i] = 0x2d
	i++
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Tickrate))))
	i += 4
	dAtA[i] = 0x30
	i++
	i = encodeVarintEngineGcmessages(dAtA, i, uint64(m.Tick))
	dAtA[i] = 0x45
	i++
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Rtdelay))))
	i += 4
	dAtA[i] = 0x4d
	i++
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Rcvage))))
	i += 4
	dAtA[i] = 0x55
	i++
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.KeyframeInterval))))
	i += 4
	return i, nil
}

func encodeVarintEngineGcmessages(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CEngineGotvSyncPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovEngineGcmessages(uint64(m.MatchId))
	n += 1 + sovEngineGcmessages(uint64(m.InstanceId))
	n += 1 + sovEngineGcmessages(uint64(m.Signupfragment))
	n += 1 + sovEngineGcmessages(uint64(m.Currentfragment))
	n += 5
	n += 1 + sovEngineGcmessages(uint64(m.Tick))
	n += 5
	n += 5
	n += 5
	return n
}

func sovEngineGcmessages(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEngineGcmessages(x uint64) (n int) {
	return sovEngineGcmessages(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CEngineGotvSyncPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEngineGcmessages
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CEngineGotvSyncPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CEngineGotvSyncPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MatchId", wireType)
			}
			m.MatchId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MatchId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstanceId", wireType)
			}
			m.InstanceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstanceId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signupfragment", wireType)
			}
			m.Signupfragment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Signupfragment |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Currentfragment", wireType)
			}
			m.Currentfragment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Currentfragment |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tickrate", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Tickrate = float32(math.Float32frombits(v))
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tick", wireType)
			}
			m.Tick = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tick |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtdelay", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Rtdelay = float32(math.Float32frombits(v))
		case 9:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rcvage", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Rcvage = float32(math.Float32frombits(v))
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyframeInterval", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.KeyframeInterval = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipEngineGcmessages(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEngineGcmessages
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEngineGcmessages
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEngineGcmessages(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEngineGcmessages
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEngineGcmessages
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEngineGcmessages
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthEngineGcmessages
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEngineGcmessages
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEngineGcmessages(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthEngineGcmessages
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEngineGcmessages = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEngineGcmessages   = fmt.Errorf("proto: integer overflow")
)
