// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: source2_steam_stats.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgSource2SystemSpecs struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuId                  *string                `protobuf:"bytes,1,opt,name=cpu_id,json=cpuId" json:"cpu_id,omitempty"`
	CpuBrand               *string                `protobuf:"bytes,2,opt,name=cpu_brand,json=cpuBrand" json:"cpu_brand,omitempty"`
	CpuModel               *uint32                `protobuf:"varint,3,opt,name=cpu_model,json=cpuModel" json:"cpu_model,omitempty"`
	CpuNumPhysical         *uint32                `protobuf:"varint,4,opt,name=cpu_num_physical,json=cpuNumPhysical" json:"cpu_num_physical,omitempty"`
	RamPhysicalTotalMb     *uint32                `protobuf:"varint,21,opt,name=ram_physical_total_mb,json=ramPhysicalTotalMb" json:"ram_physical_total_mb,omitempty"`
	GpuRendersystemDllName *string                `protobuf:"bytes,41,opt,name=gpu_rendersystem_dll_name,json=gpuRendersystemDllName" json:"gpu_rendersystem_dll_name,omitempty"`
	GpuVendorId            *uint32                `protobuf:"varint,42,opt,name=gpu_vendor_id,json=gpuVendorId" json:"gpu_vendor_id,omitempty"`
	GpuDriverName          *string                `protobuf:"bytes,43,opt,name=gpu_driver_name,json=gpuDriverName" json:"gpu_driver_name,omitempty"`
	GpuDriverVersionHigh   *uint32                `protobuf:"varint,44,opt,name=gpu_driver_version_high,json=gpuDriverVersionHigh" json:"gpu_driver_version_high,omitempty"`
	GpuDriverVersionLow    *uint32                `protobuf:"varint,45,opt,name=gpu_driver_version_low,json=gpuDriverVersionLow" json:"gpu_driver_version_low,omitempty"`
	GpuDxSupportLevel      *uint32                `protobuf:"varint,46,opt,name=gpu_dx_support_level,json=gpuDxSupportLevel" json:"gpu_dx_support_level,omitempty"`
	GpuTextureMemorySizeMb *uint32                `protobuf:"varint,47,opt,name=gpu_texture_memory_size_mb,json=gpuTextureMemorySizeMb" json:"gpu_texture_memory_size_mb,omitempty"`
	BackbufferWidth        *uint32                `protobuf:"varint,51,opt,name=backbuffer_width,json=backbufferWidth" json:"backbuffer_width,omitempty"`
	BackbufferHeight       *uint32                `protobuf:"varint,52,opt,name=backbuffer_height,json=backbufferHeight" json:"backbuffer_height,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CMsgSource2SystemSpecs) Reset() {
	*x = CMsgSource2SystemSpecs{}
	mi := &file_source2_steam_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2SystemSpecs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2SystemSpecs) ProtoMessage() {}

func (x *CMsgSource2SystemSpecs) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2SystemSpecs.ProtoReflect.Descriptor instead.
func (*CMsgSource2SystemSpecs) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgSource2SystemSpecs) GetCpuId() string {
	if x != nil && x.CpuId != nil {
		return *x.CpuId
	}
	return ""
}

func (x *CMsgSource2SystemSpecs) GetCpuBrand() string {
	if x != nil && x.CpuBrand != nil {
		return *x.CpuBrand
	}
	return ""
}

func (x *CMsgSource2SystemSpecs) GetCpuModel() uint32 {
	if x != nil && x.CpuModel != nil {
		return *x.CpuModel
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetCpuNumPhysical() uint32 {
	if x != nil && x.CpuNumPhysical != nil {
		return *x.CpuNumPhysical
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetRamPhysicalTotalMb() uint32 {
	if x != nil && x.RamPhysicalTotalMb != nil {
		return *x.RamPhysicalTotalMb
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetGpuRendersystemDllName() string {
	if x != nil && x.GpuRendersystemDllName != nil {
		return *x.GpuRendersystemDllName
	}
	return ""
}

func (x *CMsgSource2SystemSpecs) GetGpuVendorId() uint32 {
	if x != nil && x.GpuVendorId != nil {
		return *x.GpuVendorId
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetGpuDriverName() string {
	if x != nil && x.GpuDriverName != nil {
		return *x.GpuDriverName
	}
	return ""
}

func (x *CMsgSource2SystemSpecs) GetGpuDriverVersionHigh() uint32 {
	if x != nil && x.GpuDriverVersionHigh != nil {
		return *x.GpuDriverVersionHigh
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetGpuDriverVersionLow() uint32 {
	if x != nil && x.GpuDriverVersionLow != nil {
		return *x.GpuDriverVersionLow
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetGpuDxSupportLevel() uint32 {
	if x != nil && x.GpuDxSupportLevel != nil {
		return *x.GpuDxSupportLevel
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetGpuTextureMemorySizeMb() uint32 {
	if x != nil && x.GpuTextureMemorySizeMb != nil {
		return *x.GpuTextureMemorySizeMb
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetBackbufferWidth() uint32 {
	if x != nil && x.BackbufferWidth != nil {
		return *x.BackbufferWidth
	}
	return 0
}

func (x *CMsgSource2SystemSpecs) GetBackbufferHeight() uint32 {
	if x != nil && x.BackbufferHeight != nil {
		return *x.BackbufferHeight
	}
	return 0
}

type CMsgSource2VProfLiteReportItem struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ActiveSamples         *uint32                `protobuf:"varint,2,opt,name=active_samples,json=activeSamples" json:"active_samples,omitempty"`
	ActiveSamples_1Secmax *uint32                `protobuf:"varint,4,opt,name=active_samples_1secmax,json=activeSamples1secmax" json:"active_samples_1secmax,omitempty"`
	UsecMax               *uint32                `protobuf:"varint,3,opt,name=usec_max,json=usecMax" json:"usec_max,omitempty"`
	UsecAvgActive         *uint32                `protobuf:"varint,11,opt,name=usec_avg_active,json=usecAvgActive" json:"usec_avg_active,omitempty"`
	UsecP50Active         *uint32                `protobuf:"varint,12,opt,name=usec_p50_active,json=usecP50Active" json:"usec_p50_active,omitempty"`
	UsecP99Active         *uint32                `protobuf:"varint,13,opt,name=usec_p99_active,json=usecP99Active" json:"usec_p99_active,omitempty"`
	UsecAvgAll            *uint32                `protobuf:"varint,21,opt,name=usec_avg_all,json=usecAvgAll" json:"usec_avg_all,omitempty"`
	UsecP50All            *uint32                `protobuf:"varint,22,opt,name=usec_p50_all,json=usecP50All" json:"usec_p50_all,omitempty"`
	UsecP99All            *uint32                `protobuf:"varint,23,opt,name=usec_p99_all,json=usecP99All" json:"usec_p99_all,omitempty"`
	Usec_1SecmaxAvgActive *uint32                `protobuf:"varint,31,opt,name=usec_1secmax_avg_active,json=usec1secmaxAvgActive" json:"usec_1secmax_avg_active,omitempty"`
	Usec_1SecmaxP50Active *uint32                `protobuf:"varint,32,opt,name=usec_1secmax_p50_active,json=usec1secmaxP50Active" json:"usec_1secmax_p50_active,omitempty"`
	Usec_1SecmaxP95Active *uint32                `protobuf:"varint,33,opt,name=usec_1secmax_p95_active,json=usec1secmaxP95Active" json:"usec_1secmax_p95_active,omitempty"`
	Usec_1SecmaxP99Active *uint32                `protobuf:"varint,34,opt,name=usec_1secmax_p99_active,json=usec1secmaxP99Active" json:"usec_1secmax_p99_active,omitempty"`
	Usec_1SecmaxAvgAll    *uint32                `protobuf:"varint,41,opt,name=usec_1secmax_avg_all,json=usec1secmaxAvgAll" json:"usec_1secmax_avg_all,omitempty"`
	Usec_1SecmaxP50All    *uint32                `protobuf:"varint,42,opt,name=usec_1secmax_p50_all,json=usec1secmaxP50All" json:"usec_1secmax_p50_all,omitempty"`
	Usec_1SecmaxP95All    *uint32                `protobuf:"varint,43,opt,name=usec_1secmax_p95_all,json=usec1secmaxP95All" json:"usec_1secmax_p95_all,omitempty"`
	Usec_1SecmaxP99All    *uint32                `protobuf:"varint,44,opt,name=usec_1secmax_p99_all,json=usec1secmaxP99All" json:"usec_1secmax_p99_all,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CMsgSource2VProfLiteReportItem) Reset() {
	*x = CMsgSource2VProfLiteReportItem{}
	mi := &file_source2_steam_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2VProfLiteReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2VProfLiteReportItem) ProtoMessage() {}

func (x *CMsgSource2VProfLiteReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2VProfLiteReportItem.ProtoReflect.Descriptor instead.
func (*CMsgSource2VProfLiteReportItem) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgSource2VProfLiteReportItem) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CMsgSource2VProfLiteReportItem) GetActiveSamples() uint32 {
	if x != nil && x.ActiveSamples != nil {
		return *x.ActiveSamples
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetActiveSamples_1Secmax() uint32 {
	if x != nil && x.ActiveSamples_1Secmax != nil {
		return *x.ActiveSamples_1Secmax
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecMax() uint32 {
	if x != nil && x.UsecMax != nil {
		return *x.UsecMax
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecAvgActive() uint32 {
	if x != nil && x.UsecAvgActive != nil {
		return *x.UsecAvgActive
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecP50Active() uint32 {
	if x != nil && x.UsecP50Active != nil {
		return *x.UsecP50Active
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecP99Active() uint32 {
	if x != nil && x.UsecP99Active != nil {
		return *x.UsecP99Active
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecAvgAll() uint32 {
	if x != nil && x.UsecAvgAll != nil {
		return *x.UsecAvgAll
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecP50All() uint32 {
	if x != nil && x.UsecP50All != nil {
		return *x.UsecP50All
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsecP99All() uint32 {
	if x != nil && x.UsecP99All != nil {
		return *x.UsecP99All
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxAvgActive() uint32 {
	if x != nil && x.Usec_1SecmaxAvgActive != nil {
		return *x.Usec_1SecmaxAvgActive
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP50Active() uint32 {
	if x != nil && x.Usec_1SecmaxP50Active != nil {
		return *x.Usec_1SecmaxP50Active
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP95Active() uint32 {
	if x != nil && x.Usec_1SecmaxP95Active != nil {
		return *x.Usec_1SecmaxP95Active
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP99Active() uint32 {
	if x != nil && x.Usec_1SecmaxP99Active != nil {
		return *x.Usec_1SecmaxP99Active
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxAvgAll() uint32 {
	if x != nil && x.Usec_1SecmaxAvgAll != nil {
		return *x.Usec_1SecmaxAvgAll
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP50All() uint32 {
	if x != nil && x.Usec_1SecmaxP50All != nil {
		return *x.Usec_1SecmaxP50All
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP95All() uint32 {
	if x != nil && x.Usec_1SecmaxP95All != nil {
		return *x.Usec_1SecmaxP95All
	}
	return 0
}

func (x *CMsgSource2VProfLiteReportItem) GetUsec_1SecmaxP99All() uint32 {
	if x != nil && x.Usec_1SecmaxP99All != nil {
		return *x.Usec_1SecmaxP99All
	}
	return 0
}

type CMsgSource2VProfLiteReport struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	Total           *CMsgSource2VProfLiteReportItem   `protobuf:"bytes,1,opt,name=total" json:"total,omitempty"`
	Items           []*CMsgSource2VProfLiteReportItem `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	DiscardedFrames *uint32                           `protobuf:"varint,3,opt,name=discarded_frames,json=discardedFrames" json:"discarded_frames,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CMsgSource2VProfLiteReport) Reset() {
	*x = CMsgSource2VProfLiteReport{}
	mi := &file_source2_steam_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2VProfLiteReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2VProfLiteReport) ProtoMessage() {}

func (x *CMsgSource2VProfLiteReport) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2VProfLiteReport.ProtoReflect.Descriptor instead.
func (*CMsgSource2VProfLiteReport) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgSource2VProfLiteReport) GetTotal() *CMsgSource2VProfLiteReportItem {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *CMsgSource2VProfLiteReport) GetItems() []*CMsgSource2VProfLiteReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CMsgSource2VProfLiteReport) GetDiscardedFrames() uint32 {
	if x != nil && x.DiscardedFrames != nil {
		return *x.DiscardedFrames
	}
	return 0
}

type CMsgSource2NetworkFlowQuality struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Duration                      *uint32                `protobuf:"varint,1,opt,name=duration" json:"duration,omitempty"`
	BytesTotal                    *uint64                `protobuf:"varint,5,opt,name=bytes_total,json=bytesTotal" json:"bytes_total,omitempty"`
	BytesTotalReliable            *uint64                `protobuf:"varint,6,opt,name=bytes_total_reliable,json=bytesTotalReliable" json:"bytes_total_reliable,omitempty"`
	BytesTotalVoice               *uint64                `protobuf:"varint,7,opt,name=bytes_total_voice,json=bytesTotalVoice" json:"bytes_total_voice,omitempty"`
	BytesSecP95                   *uint32                `protobuf:"varint,10,opt,name=bytes_sec_p95,json=bytesSecP95" json:"bytes_sec_p95,omitempty"`
	BytesSecP99                   *uint32                `protobuf:"varint,11,opt,name=bytes_sec_p99,json=bytesSecP99" json:"bytes_sec_p99,omitempty"`
	EnginemsgsTotal               *uint32                `protobuf:"varint,20,opt,name=enginemsgs_total,json=enginemsgsTotal" json:"enginemsgs_total,omitempty"`
	EnginemsgsSecP95              *uint32                `protobuf:"varint,21,opt,name=enginemsgs_sec_p95,json=enginemsgsSecP95" json:"enginemsgs_sec_p95,omitempty"`
	EnginemsgsSecP99              *uint32                `protobuf:"varint,22,opt,name=enginemsgs_sec_p99,json=enginemsgsSecP99" json:"enginemsgs_sec_p99,omitempty"`
	NetframesTotal                *uint32                `protobuf:"varint,30,opt,name=netframes_total,json=netframesTotal" json:"netframes_total,omitempty"`
	NetframesDropped              *uint32                `protobuf:"varint,31,opt,name=netframes_dropped,json=netframesDropped" json:"netframes_dropped,omitempty"`
	NetframesOutoforder           *uint32                `protobuf:"varint,32,opt,name=netframes_outoforder,json=netframesOutoforder" json:"netframes_outoforder,omitempty"`
	NetframesSizeExceedsMtu       *uint32                `protobuf:"varint,34,opt,name=netframes_size_exceeds_mtu,json=netframesSizeExceedsMtu" json:"netframes_size_exceeds_mtu,omitempty"`
	NetframesSizeP95              *uint32                `protobuf:"varint,35,opt,name=netframes_size_p95,json=netframesSizeP95" json:"netframes_size_p95,omitempty"`
	NetframesSizeP99              *uint32                `protobuf:"varint,36,opt,name=netframes_size_p99,json=netframesSizeP99" json:"netframes_size_p99,omitempty"`
	TicksTotal                    *uint32                `protobuf:"varint,40,opt,name=ticks_total,json=ticksTotal" json:"ticks_total,omitempty"`
	TicksGood                     *uint32                `protobuf:"varint,41,opt,name=ticks_good,json=ticksGood" json:"ticks_good,omitempty"`
	TicksGoodAlmostLate           *uint32                `protobuf:"varint,42,opt,name=ticks_good_almost_late,json=ticksGoodAlmostLate" json:"ticks_good_almost_late,omitempty"`
	TicksFixedDropped             *uint32                `protobuf:"varint,43,opt,name=ticks_fixed_dropped,json=ticksFixedDropped" json:"ticks_fixed_dropped,omitempty"`
	TicksFixedLate                *uint32                `protobuf:"varint,44,opt,name=ticks_fixed_late,json=ticksFixedLate" json:"ticks_fixed_late,omitempty"`
	TicksBadDropped               *uint32                `protobuf:"varint,45,opt,name=ticks_bad_dropped,json=ticksBadDropped" json:"ticks_bad_dropped,omitempty"`
	TicksBadLate                  *uint32                `protobuf:"varint,46,opt,name=ticks_bad_late,json=ticksBadLate" json:"ticks_bad_late,omitempty"`
	TicksBadOther                 *uint32                `protobuf:"varint,47,opt,name=ticks_bad_other,json=ticksBadOther" json:"ticks_bad_other,omitempty"`
	TickMissrateSamplesTotal      *uint32                `protobuf:"varint,50,opt,name=tick_missrate_samples_total,json=tickMissrateSamplesTotal" json:"tick_missrate_samples_total,omitempty"`
	TickMissrateSamplesPerfect    *uint32                `protobuf:"varint,51,opt,name=tick_missrate_samples_perfect,json=tickMissrateSamplesPerfect" json:"tick_missrate_samples_perfect,omitempty"`
	TickMissrateSamplesPerfectnet *uint32                `protobuf:"varint,52,opt,name=tick_missrate_samples_perfectnet,json=tickMissrateSamplesPerfectnet" json:"tick_missrate_samples_perfectnet,omitempty"`
	TickMissratenetP75X10         *uint32                `protobuf:"varint,53,opt,name=tick_missratenet_p75_x10,json=tickMissratenetP75X10" json:"tick_missratenet_p75_x10,omitempty"`
	TickMissratenetP95X10         *uint32                `protobuf:"varint,54,opt,name=tick_missratenet_p95_x10,json=tickMissratenetP95X10" json:"tick_missratenet_p95_x10,omitempty"`
	TickMissratenetP99X10         *uint32                `protobuf:"varint,55,opt,name=tick_missratenet_p99_x10,json=tickMissratenetP99X10" json:"tick_missratenet_p99_x10,omitempty"`
	RecvmarginP1                  *int32                 `protobuf:"zigzag32,61,opt,name=recvmargin_p1,json=recvmarginP1" json:"recvmargin_p1,omitempty"`
	RecvmarginP5                  *int32                 `protobuf:"zigzag32,62,opt,name=recvmargin_p5,json=recvmarginP5" json:"recvmargin_p5,omitempty"`
	RecvmarginP25                 *int32                 `protobuf:"zigzag32,63,opt,name=recvmargin_p25,json=recvmarginP25" json:"recvmargin_p25,omitempty"`
	RecvmarginP50                 *int32                 `protobuf:"zigzag32,64,opt,name=recvmargin_p50,json=recvmarginP50" json:"recvmargin_p50,omitempty"`
	RecvmarginP75                 *int32                 `protobuf:"zigzag32,65,opt,name=recvmargin_p75,json=recvmarginP75" json:"recvmargin_p75,omitempty"`
	RecvmarginP95                 *int32                 `protobuf:"zigzag32,66,opt,name=recvmargin_p95,json=recvmarginP95" json:"recvmargin_p95,omitempty"`
	NetframeJitterP50             *uint32                `protobuf:"varint,70,opt,name=netframe_jitter_p50,json=netframeJitterP50" json:"netframe_jitter_p50,omitempty"`
	NetframeJitterP99             *uint32                `protobuf:"varint,71,opt,name=netframe_jitter_p99,json=netframeJitterP99" json:"netframe_jitter_p99,omitempty"`
	IntervalPeakjitterP50         *uint32                `protobuf:"varint,72,opt,name=interval_peakjitter_p50,json=intervalPeakjitterP50" json:"interval_peakjitter_p50,omitempty"`
	IntervalPeakjitterP95         *uint32                `protobuf:"varint,73,opt,name=interval_peakjitter_p95,json=intervalPeakjitterP95" json:"interval_peakjitter_p95,omitempty"`
	PacketMisdeliveryRateP50X4    *uint32                `protobuf:"varint,74,opt,name=packet_misdelivery_rate_p50_x4,json=packetMisdeliveryRateP50X4" json:"packet_misdelivery_rate_p50_x4,omitempty"`
	PacketMisdeliveryRateP95X4    *uint32                `protobuf:"varint,75,opt,name=packet_misdelivery_rate_p95_x4,json=packetMisdeliveryRateP95X4" json:"packet_misdelivery_rate_p95_x4,omitempty"`
	NetPingP5                     *uint32                `protobuf:"varint,80,opt,name=net_ping_p5,json=netPingP5" json:"net_ping_p5,omitempty"`
	NetPingP50                    *uint32                `protobuf:"varint,81,opt,name=net_ping_p50,json=netPingP50" json:"net_ping_p50,omitempty"`
	NetPingP95                    *uint32                `protobuf:"varint,82,opt,name=net_ping_p95,json=netPingP95" json:"net_ping_p95,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CMsgSource2NetworkFlowQuality) Reset() {
	*x = CMsgSource2NetworkFlowQuality{}
	mi := &file_source2_steam_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2NetworkFlowQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2NetworkFlowQuality) ProtoMessage() {}

func (x *CMsgSource2NetworkFlowQuality) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2NetworkFlowQuality.ProtoReflect.Descriptor instead.
func (*CMsgSource2NetworkFlowQuality) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgSource2NetworkFlowQuality) GetDuration() uint32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetBytesTotal() uint64 {
	if x != nil && x.BytesTotal != nil {
		return *x.BytesTotal
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetBytesTotalReliable() uint64 {
	if x != nil && x.BytesTotalReliable != nil {
		return *x.BytesTotalReliable
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetBytesTotalVoice() uint64 {
	if x != nil && x.BytesTotalVoice != nil {
		return *x.BytesTotalVoice
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetBytesSecP95() uint32 {
	if x != nil && x.BytesSecP95 != nil {
		return *x.BytesSecP95
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetBytesSecP99() uint32 {
	if x != nil && x.BytesSecP99 != nil {
		return *x.BytesSecP99
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetEnginemsgsTotal() uint32 {
	if x != nil && x.EnginemsgsTotal != nil {
		return *x.EnginemsgsTotal
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetEnginemsgsSecP95() uint32 {
	if x != nil && x.EnginemsgsSecP95 != nil {
		return *x.EnginemsgsSecP95
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetEnginemsgsSecP99() uint32 {
	if x != nil && x.EnginemsgsSecP99 != nil {
		return *x.EnginemsgsSecP99
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesTotal() uint32 {
	if x != nil && x.NetframesTotal != nil {
		return *x.NetframesTotal
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesDropped() uint32 {
	if x != nil && x.NetframesDropped != nil {
		return *x.NetframesDropped
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesOutoforder() uint32 {
	if x != nil && x.NetframesOutoforder != nil {
		return *x.NetframesOutoforder
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesSizeExceedsMtu() uint32 {
	if x != nil && x.NetframesSizeExceedsMtu != nil {
		return *x.NetframesSizeExceedsMtu
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesSizeP95() uint32 {
	if x != nil && x.NetframesSizeP95 != nil {
		return *x.NetframesSizeP95
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframesSizeP99() uint32 {
	if x != nil && x.NetframesSizeP99 != nil {
		return *x.NetframesSizeP99
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksTotal() uint32 {
	if x != nil && x.TicksTotal != nil {
		return *x.TicksTotal
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksGood() uint32 {
	if x != nil && x.TicksGood != nil {
		return *x.TicksGood
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksGoodAlmostLate() uint32 {
	if x != nil && x.TicksGoodAlmostLate != nil {
		return *x.TicksGoodAlmostLate
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksFixedDropped() uint32 {
	if x != nil && x.TicksFixedDropped != nil {
		return *x.TicksFixedDropped
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksFixedLate() uint32 {
	if x != nil && x.TicksFixedLate != nil {
		return *x.TicksFixedLate
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksBadDropped() uint32 {
	if x != nil && x.TicksBadDropped != nil {
		return *x.TicksBadDropped
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksBadLate() uint32 {
	if x != nil && x.TicksBadLate != nil {
		return *x.TicksBadLate
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTicksBadOther() uint32 {
	if x != nil && x.TicksBadOther != nil {
		return *x.TicksBadOther
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissrateSamplesTotal() uint32 {
	if x != nil && x.TickMissrateSamplesTotal != nil {
		return *x.TickMissrateSamplesTotal
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissrateSamplesPerfect() uint32 {
	if x != nil && x.TickMissrateSamplesPerfect != nil {
		return *x.TickMissrateSamplesPerfect
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissrateSamplesPerfectnet() uint32 {
	if x != nil && x.TickMissrateSamplesPerfectnet != nil {
		return *x.TickMissrateSamplesPerfectnet
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissratenetP75X10() uint32 {
	if x != nil && x.TickMissratenetP75X10 != nil {
		return *x.TickMissratenetP75X10
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissratenetP95X10() uint32 {
	if x != nil && x.TickMissratenetP95X10 != nil {
		return *x.TickMissratenetP95X10
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetTickMissratenetP99X10() uint32 {
	if x != nil && x.TickMissratenetP99X10 != nil {
		return *x.TickMissratenetP99X10
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP1() int32 {
	if x != nil && x.RecvmarginP1 != nil {
		return *x.RecvmarginP1
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP5() int32 {
	if x != nil && x.RecvmarginP5 != nil {
		return *x.RecvmarginP5
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP25() int32 {
	if x != nil && x.RecvmarginP25 != nil {
		return *x.RecvmarginP25
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP50() int32 {
	if x != nil && x.RecvmarginP50 != nil {
		return *x.RecvmarginP50
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP75() int32 {
	if x != nil && x.RecvmarginP75 != nil {
		return *x.RecvmarginP75
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetRecvmarginP95() int32 {
	if x != nil && x.RecvmarginP95 != nil {
		return *x.RecvmarginP95
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframeJitterP50() uint32 {
	if x != nil && x.NetframeJitterP50 != nil {
		return *x.NetframeJitterP50
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetframeJitterP99() uint32 {
	if x != nil && x.NetframeJitterP99 != nil {
		return *x.NetframeJitterP99
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetIntervalPeakjitterP50() uint32 {
	if x != nil && x.IntervalPeakjitterP50 != nil {
		return *x.IntervalPeakjitterP50
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetIntervalPeakjitterP95() uint32 {
	if x != nil && x.IntervalPeakjitterP95 != nil {
		return *x.IntervalPeakjitterP95
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetPacketMisdeliveryRateP50X4() uint32 {
	if x != nil && x.PacketMisdeliveryRateP50X4 != nil {
		return *x.PacketMisdeliveryRateP50X4
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetPacketMisdeliveryRateP95X4() uint32 {
	if x != nil && x.PacketMisdeliveryRateP95X4 != nil {
		return *x.PacketMisdeliveryRateP95X4
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetPingP5() uint32 {
	if x != nil && x.NetPingP5 != nil {
		return *x.NetPingP5
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetPingP50() uint32 {
	if x != nil && x.NetPingP50 != nil {
		return *x.NetPingP50
	}
	return 0
}

func (x *CMsgSource2NetworkFlowQuality) GetNetPingP95() uint32 {
	if x != nil && x.NetPingP95 != nil {
		return *x.NetPingP95
	}
	return 0
}

type CMsgSource2PerfIntervalSample struct {
	state            protoimpl.MessageState               `protogen:"open.v1"`
	FrameTimeMaxMs   *float32                             `protobuf:"fixed32,1,opt,name=frame_time_max_ms,json=frameTimeMaxMs" json:"frame_time_max_ms,omitempty"`
	FrameTimeAvgMs   *float32                             `protobuf:"fixed32,2,opt,name=frame_time_avg_ms,json=frameTimeAvgMs" json:"frame_time_avg_ms,omitempty"`
	FrameTimeMinMs   *float32                             `protobuf:"fixed32,3,opt,name=frame_time_min_ms,json=frameTimeMinMs" json:"frame_time_min_ms,omitempty"`
	FrameCount       *int32                               `protobuf:"varint,4,opt,name=frame_count,json=frameCount" json:"frame_count,omitempty"`
	FrameTimeTotalMs *float32                             `protobuf:"fixed32,5,opt,name=frame_time_total_ms,json=frameTimeTotalMs" json:"frame_time_total_ms,omitempty"`
	Tags             []*CMsgSource2PerfIntervalSample_Tag `protobuf:"bytes,6,rep,name=tags" json:"tags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CMsgSource2PerfIntervalSample) Reset() {
	*x = CMsgSource2PerfIntervalSample{}
	mi := &file_source2_steam_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2PerfIntervalSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2PerfIntervalSample) ProtoMessage() {}

func (x *CMsgSource2PerfIntervalSample) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2PerfIntervalSample.ProtoReflect.Descriptor instead.
func (*CMsgSource2PerfIntervalSample) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgSource2PerfIntervalSample) GetFrameTimeMaxMs() float32 {
	if x != nil && x.FrameTimeMaxMs != nil {
		return *x.FrameTimeMaxMs
	}
	return 0
}

func (x *CMsgSource2PerfIntervalSample) GetFrameTimeAvgMs() float32 {
	if x != nil && x.FrameTimeAvgMs != nil {
		return *x.FrameTimeAvgMs
	}
	return 0
}

func (x *CMsgSource2PerfIntervalSample) GetFrameTimeMinMs() float32 {
	if x != nil && x.FrameTimeMinMs != nil {
		return *x.FrameTimeMinMs
	}
	return 0
}

func (x *CMsgSource2PerfIntervalSample) GetFrameCount() int32 {
	if x != nil && x.FrameCount != nil {
		return *x.FrameCount
	}
	return 0
}

func (x *CMsgSource2PerfIntervalSample) GetFrameTimeTotalMs() float32 {
	if x != nil && x.FrameTimeTotalMs != nil {
		return *x.FrameTimeTotalMs
	}
	return 0
}

func (x *CMsgSource2PerfIntervalSample) GetTags() []*CMsgSource2PerfIntervalSample_Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CSource2Metrics_MatchPerfSummary_Notification struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Appid         *uint32                                                 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	GameMode      *string                                                 `protobuf:"bytes,2,opt,name=game_mode,json=gameMode" json:"game_mode,omitempty"`
	ServerBuildId *uint32                                                 `protobuf:"varint,3,opt,name=server_build_id,json=serverBuildId" json:"server_build_id,omitempty"`
	ServerPopid   *uint32                                                 `protobuf:"fixed32,4,opt,name=server_popid,json=serverPopid" json:"server_popid,omitempty"`
	ServerProfile *CMsgSource2VProfLiteReport                             `protobuf:"bytes,10,opt,name=server_profile,json=serverProfile" json:"server_profile,omitempty"`
	Clients       []*CSource2Metrics_MatchPerfSummary_Notification_Client `protobuf:"bytes,11,rep,name=clients" json:"clients,omitempty"`
	Map           *string                                                 `protobuf:"bytes,20,opt,name=map" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) Reset() {
	*x = CSource2Metrics_MatchPerfSummary_Notification{}
	mi := &file_source2_steam_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSource2Metrics_MatchPerfSummary_Notification) ProtoMessage() {}

func (x *CSource2Metrics_MatchPerfSummary_Notification) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSource2Metrics_MatchPerfSummary_Notification.ProtoReflect.Descriptor instead.
func (*CSource2Metrics_MatchPerfSummary_Notification) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{5}
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetAppid() uint32 {
	if x != nil && x.Appid != nil {
		return *x.Appid
	}
	return 0
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetGameMode() string {
	if x != nil && x.GameMode != nil {
		return *x.GameMode
	}
	return ""
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetServerBuildId() uint32 {
	if x != nil && x.ServerBuildId != nil {
		return *x.ServerBuildId
	}
	return 0
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetServerPopid() uint32 {
	if x != nil && x.ServerPopid != nil {
		return *x.ServerPopid
	}
	return 0
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetServerProfile() *CMsgSource2VProfLiteReport {
	if x != nil {
		return x.ServerProfile
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetClients() []*CSource2Metrics_MatchPerfSummary_Notification_Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification) GetMap() string {
	if x != nil && x.Map != nil {
		return *x.Map
	}
	return ""
}

type CMsgSource2PerfIntervalSample_Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *string                `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	MaxValue      *uint32                `protobuf:"varint,2,opt,name=max_value,json=maxValue" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgSource2PerfIntervalSample_Tag) Reset() {
	*x = CMsgSource2PerfIntervalSample_Tag{}
	mi := &file_source2_steam_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgSource2PerfIntervalSample_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgSource2PerfIntervalSample_Tag) ProtoMessage() {}

func (x *CMsgSource2PerfIntervalSample_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgSource2PerfIntervalSample_Tag.ProtoReflect.Descriptor instead.
func (*CMsgSource2PerfIntervalSample_Tag) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CMsgSource2PerfIntervalSample_Tag) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *CMsgSource2PerfIntervalSample_Tag) GetMaxValue() uint32 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

type CSource2Metrics_MatchPerfSummary_Notification_Client struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	SystemSpecs    *CMsgSource2SystemSpecs          `protobuf:"bytes,1,opt,name=system_specs,json=systemSpecs" json:"system_specs,omitempty"`
	Profile        *CMsgSource2VProfLiteReport      `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
	BuildId        *uint32                          `protobuf:"varint,3,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	DownstreamFlow *CMsgSource2NetworkFlowQuality   `protobuf:"bytes,4,opt,name=downstream_flow,json=downstreamFlow" json:"downstream_flow,omitempty"`
	UpstreamFlow   *CMsgSource2NetworkFlowQuality   `protobuf:"bytes,5,opt,name=upstream_flow,json=upstreamFlow" json:"upstream_flow,omitempty"`
	Steamid        *uint64                          `protobuf:"fixed64,10,opt,name=steamid" json:"steamid,omitempty"`
	PerfSamples    []*CMsgSource2PerfIntervalSample `protobuf:"bytes,11,rep,name=perf_samples,json=perfSamples" json:"perf_samples,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) Reset() {
	*x = CSource2Metrics_MatchPerfSummary_Notification_Client{}
	mi := &file_source2_steam_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSource2Metrics_MatchPerfSummary_Notification_Client) ProtoMessage() {}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) ProtoReflect() protoreflect.Message {
	mi := &file_source2_steam_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSource2Metrics_MatchPerfSummary_Notification_Client.ProtoReflect.Descriptor instead.
func (*CSource2Metrics_MatchPerfSummary_Notification_Client) Descriptor() ([]byte, []int) {
	return file_source2_steam_stats_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetSystemSpecs() *CMsgSource2SystemSpecs {
	if x != nil {
		return x.SystemSpecs
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetProfile() *CMsgSource2VProfLiteReport {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetBuildId() uint32 {
	if x != nil && x.BuildId != nil {
		return *x.BuildId
	}
	return 0
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetDownstreamFlow() *CMsgSource2NetworkFlowQuality {
	if x != nil {
		return x.DownstreamFlow
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetUpstreamFlow() *CMsgSource2NetworkFlowQuality {
	if x != nil {
		return x.UpstreamFlow
	}
	return nil
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetSteamid() uint64 {
	if x != nil && x.Steamid != nil {
		return *x.Steamid
	}
	return 0
}

func (x *CSource2Metrics_MatchPerfSummary_Notification_Client) GetPerfSamples() []*CMsgSource2PerfIntervalSample {
	if x != nil {
		return x.PerfSamples
	}
	return nil
}

var File_source2_steam_stats_proto protoreflect.FileDescriptor

const file_source2_steam_stats_proto_rawDesc = "" +
	"\n" +
	"\x19source2_steam_stats.proto\"\xfe\x04\n" +
	"\x16CMsgSource2SystemSpecs\x12\x15\n" +
	"\x06cpu_id\x18\x01 \x01(\tR\x05cpuId\x12\x1b\n" +
	"\tcpu_brand\x18\x02 \x01(\tR\bcpuBrand\x12\x1b\n" +
	"\tcpu_model\x18\x03 \x01(\rR\bcpuModel\x12(\n" +
	"\x10cpu_num_physical\x18\x04 \x01(\rR\x0ecpuNumPhysical\x121\n" +
	"\x15ram_physical_total_mb\x18\x15 \x01(\rR\x12ramPhysicalTotalMb\x129\n" +
	"\x19gpu_rendersystem_dll_name\x18) \x01(\tR\x16gpuRendersystemDllName\x12\"\n" +
	"\rgpu_vendor_id\x18* \x01(\rR\vgpuVendorId\x12&\n" +
	"\x0fgpu_driver_name\x18+ \x01(\tR\rgpuDriverName\x125\n" +
	"\x17gpu_driver_version_high\x18, \x01(\rR\x14gpuDriverVersionHigh\x123\n" +
	"\x16gpu_driver_version_low\x18- \x01(\rR\x13gpuDriverVersionLow\x12/\n" +
	"\x14gpu_dx_support_level\x18. \x01(\rR\x11gpuDxSupportLevel\x12:\n" +
	"\x1agpu_texture_memory_size_mb\x18/ \x01(\rR\x16gpuTextureMemorySizeMb\x12)\n" +
	"\x10backbuffer_width\x183 \x01(\rR\x0fbackbufferWidth\x12+\n" +
	"\x11backbuffer_height\x184 \x01(\rR\x10backbufferHeight\"\xaa\x06\n" +
	"\x1eCMsgSource2VProfLiteReportItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eactive_samples\x18\x02 \x01(\rR\ractiveSamples\x124\n" +
	"\x16active_samples_1secmax\x18\x04 \x01(\rR\x14activeSamples1secmax\x12\x19\n" +
	"\busec_max\x18\x03 \x01(\rR\ausecMax\x12&\n" +
	"\x0fusec_avg_active\x18\v \x01(\rR\rusecAvgActive\x12&\n" +
	"\x0fusec_p50_active\x18\f \x01(\rR\rusecP50Active\x12&\n" +
	"\x0fusec_p99_active\x18\r \x01(\rR\rusecP99Active\x12 \n" +
	"\fusec_avg_all\x18\x15 \x01(\rR\n" +
	"usecAvgAll\x12 \n" +
	"\fusec_p50_all\x18\x16 \x01(\rR\n" +
	"usecP50All\x12 \n" +
	"\fusec_p99_all\x18\x17 \x01(\rR\n" +
	"usecP99All\x125\n" +
	"\x17usec_1secmax_avg_active\x18\x1f \x01(\rR\x14usec1secmaxAvgActive\x125\n" +
	"\x17usec_1secmax_p50_active\x18  \x01(\rR\x14usec1secmaxP50Active\x125\n" +
	"\x17usec_1secmax_p95_active\x18! \x01(\rR\x14usec1secmaxP95Active\x125\n" +
	"\x17usec_1secmax_p99_active\x18\" \x01(\rR\x14usec1secmaxP99Active\x12/\n" +
	"\x14usec_1secmax_avg_all\x18) \x01(\rR\x11usec1secmaxAvgAll\x12/\n" +
	"\x14usec_1secmax_p50_all\x18* \x01(\rR\x11usec1secmaxP50All\x12/\n" +
	"\x14usec_1secmax_p95_all\x18+ \x01(\rR\x11usec1secmaxP95All\x12/\n" +
	"\x14usec_1secmax_p99_all\x18, \x01(\rR\x11usec1secmaxP99All\"\xb5\x01\n" +
	"\x1aCMsgSource2VProfLiteReport\x125\n" +
	"\x05total\x18\x01 \x01(\v2\x1f.CMsgSource2VProfLiteReportItemR\x05total\x125\n" +
	"\x05items\x18\x02 \x03(\v2\x1f.CMsgSource2VProfLiteReportItemR\x05items\x12)\n" +
	"\x10discarded_frames\x18\x03 \x01(\rR\x0fdiscardedFrames\"\x8c\x10\n" +
	"\x1dCMsgSource2NetworkFlowQuality\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\rR\bduration\x12\x1f\n" +
	"\vbytes_total\x18\x05 \x01(\x04R\n" +
	"bytesTotal\x120\n" +
	"\x14bytes_total_reliable\x18\x06 \x01(\x04R\x12bytesTotalReliable\x12*\n" +
	"\x11bytes_total_voice\x18\a \x01(\x04R\x0fbytesTotalVoice\x12\"\n" +
	"\rbytes_sec_p95\x18\n" +
	" \x01(\rR\vbytesSecP95\x12\"\n" +
	"\rbytes_sec_p99\x18\v \x01(\rR\vbytesSecP99\x12)\n" +
	"\x10enginemsgs_total\x18\x14 \x01(\rR\x0fenginemsgsTotal\x12,\n" +
	"\x12enginemsgs_sec_p95\x18\x15 \x01(\rR\x10enginemsgsSecP95\x12,\n" +
	"\x12enginemsgs_sec_p99\x18\x16 \x01(\rR\x10enginemsgsSecP99\x12'\n" +
	"\x0fnetframes_total\x18\x1e \x01(\rR\x0enetframesTotal\x12+\n" +
	"\x11netframes_dropped\x18\x1f \x01(\rR\x10netframesDropped\x121\n" +
	"\x14netframes_outoforder\x18  \x01(\rR\x13netframesOutoforder\x12;\n" +
	"\x1anetframes_size_exceeds_mtu\x18\" \x01(\rR\x17netframesSizeExceedsMtu\x12,\n" +
	"\x12netframes_size_p95\x18# \x01(\rR\x10netframesSizeP95\x12,\n" +
	"\x12netframes_size_p99\x18$ \x01(\rR\x10netframesSizeP99\x12\x1f\n" +
	"\vticks_total\x18( \x01(\rR\n" +
	"ticksTotal\x12\x1d\n" +
	"\n" +
	"ticks_good\x18) \x01(\rR\tticksGood\x123\n" +
	"\x16ticks_good_almost_late\x18* \x01(\rR\x13ticksGoodAlmostLate\x12.\n" +
	"\x13ticks_fixed_dropped\x18+ \x01(\rR\x11ticksFixedDropped\x12(\n" +
	"\x10ticks_fixed_late\x18, \x01(\rR\x0eticksFixedLate\x12*\n" +
	"\x11ticks_bad_dropped\x18- \x01(\rR\x0fticksBadDropped\x12$\n" +
	"\x0eticks_bad_late\x18. \x01(\rR\fticksBadLate\x12&\n" +
	"\x0fticks_bad_other\x18/ \x01(\rR\rticksBadOther\x12=\n" +
	"\x1btick_missrate_samples_total\x182 \x01(\rR\x18tickMissrateSamplesTotal\x12A\n" +
	"\x1dtick_missrate_samples_perfect\x183 \x01(\rR\x1atickMissrateSamplesPerfect\x12G\n" +
	" tick_missrate_samples_perfectnet\x184 \x01(\rR\x1dtickMissrateSamplesPerfectnet\x127\n" +
	"\x18tick_missratenet_p75_x10\x185 \x01(\rR\x15tickMissratenetP75X10\x127\n" +
	"\x18tick_missratenet_p95_x10\x186 \x01(\rR\x15tickMissratenetP95X10\x127\n" +
	"\x18tick_missratenet_p99_x10\x187 \x01(\rR\x15tickMissratenetP99X10\x12#\n" +
	"\rrecvmargin_p1\x18= \x01(\x11R\frecvmarginP1\x12#\n" +
	"\rrecvmargin_p5\x18> \x01(\x11R\frecvmarginP5\x12%\n" +
	"\x0erecvmargin_p25\x18? \x01(\x11R\rrecvmarginP25\x12%\n" +
	"\x0erecvmargin_p50\x18@ \x01(\x11R\rrecvmarginP50\x12%\n" +
	"\x0erecvmargin_p75\x18A \x01(\x11R\rrecvmarginP75\x12%\n" +
	"\x0erecvmargin_p95\x18B \x01(\x11R\rrecvmarginP95\x12.\n" +
	"\x13netframe_jitter_p50\x18F \x01(\rR\x11netframeJitterP50\x12.\n" +
	"\x13netframe_jitter_p99\x18G \x01(\rR\x11netframeJitterP99\x126\n" +
	"\x17interval_peakjitter_p50\x18H \x01(\rR\x15intervalPeakjitterP50\x126\n" +
	"\x17interval_peakjitter_p95\x18I \x01(\rR\x15intervalPeakjitterP95\x12B\n" +
	"\x1epacket_misdelivery_rate_p50_x4\x18J \x01(\rR\x1apacketMisdeliveryRateP50X4\x12B\n" +
	"\x1epacket_misdelivery_rate_p95_x4\x18K \x01(\rR\x1apacketMisdeliveryRateP95X4\x12\x1e\n" +
	"\vnet_ping_p5\x18P \x01(\rR\tnetPingP5\x12 \n" +
	"\fnet_ping_p50\x18Q \x01(\rR\n" +
	"netPingP50\x12 \n" +
	"\fnet_ping_p95\x18R \x01(\rR\n" +
	"netPingP95\"\xde\x02\n" +
	"\x1dCMsgSource2PerfIntervalSample\x12)\n" +
	"\x11frame_time_max_ms\x18\x01 \x01(\x02R\x0eframeTimeMaxMs\x12)\n" +
	"\x11frame_time_avg_ms\x18\x02 \x01(\x02R\x0eframeTimeAvgMs\x12)\n" +
	"\x11frame_time_min_ms\x18\x03 \x01(\x02R\x0eframeTimeMinMs\x12\x1f\n" +
	"\vframe_count\x18\x04 \x01(\x05R\n" +
	"frameCount\x12-\n" +
	"\x13frame_time_total_ms\x18\x05 \x01(\x02R\x10frameTimeTotalMs\x126\n" +
	"\x04tags\x18\x06 \x03(\v2\".CMsgSource2PerfIntervalSample.TagR\x04tags\x1a4\n" +
	"\x03Tag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x1b\n" +
	"\tmax_value\x18\x02 \x01(\rR\bmaxValue\"\xd8\x05\n" +
	"-CSource2Metrics_MatchPerfSummary_Notification\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\rR\x05appid\x12\x1b\n" +
	"\tgame_mode\x18\x02 \x01(\tR\bgameMode\x12&\n" +
	"\x0fserver_build_id\x18\x03 \x01(\rR\rserverBuildId\x12!\n" +
	"\fserver_popid\x18\x04 \x01(\aR\vserverPopid\x12B\n" +
	"\x0eserver_profile\x18\n" +
	" \x01(\v2\x1b.CMsgSource2VProfLiteReportR\rserverProfile\x12O\n" +
	"\aclients\x18\v \x03(\v25.CSource2Metrics_MatchPerfSummary_Notification.ClientR\aclients\x12\x10\n" +
	"\x03map\x18\x14 \x01(\tR\x03map\x1a\x81\x03\n" +
	"\x06Client\x12:\n" +
	"\fsystem_specs\x18\x01 \x01(\v2\x17.CMsgSource2SystemSpecsR\vsystemSpecs\x125\n" +
	"\aprofile\x18\x02 \x01(\v2\x1b.CMsgSource2VProfLiteReportR\aprofile\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\rR\abuildId\x12G\n" +
	"\x0fdownstream_flow\x18\x04 \x01(\v2\x1e.CMsgSource2NetworkFlowQualityR\x0edownstreamFlow\x12C\n" +
	"\rupstream_flow\x18\x05 \x01(\v2\x1e.CMsgSource2NetworkFlowQualityR\fupstreamFlow\x12\x18\n" +
	"\asteamid\x18\n" +
	" \x01(\x06R\asteamid\x12A\n" +
	"\fperf_samples\x18\v \x03(\v2\x1e.CMsgSource2PerfIntervalSampleR\vperfSamples"

var (
	file_source2_steam_stats_proto_rawDescOnce sync.Once
	file_source2_steam_stats_proto_rawDescData []byte
)

func file_source2_steam_stats_proto_rawDescGZIP() []byte {
	file_source2_steam_stats_proto_rawDescOnce.Do(func() {
		file_source2_steam_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_source2_steam_stats_proto_rawDesc), len(file_source2_steam_stats_proto_rawDesc)))
	})
	return file_source2_steam_stats_proto_rawDescData
}

var file_source2_steam_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_source2_steam_stats_proto_goTypes = []any{
	(*CMsgSource2SystemSpecs)(nil),                               // 0: CMsgSource2SystemSpecs
	(*CMsgSource2VProfLiteReportItem)(nil),                       // 1: CMsgSource2VProfLiteReportItem
	(*CMsgSource2VProfLiteReport)(nil),                           // 2: CMsgSource2VProfLiteReport
	(*CMsgSource2NetworkFlowQuality)(nil),                        // 3: CMsgSource2NetworkFlowQuality
	(*CMsgSource2PerfIntervalSample)(nil),                        // 4: CMsgSource2PerfIntervalSample
	(*CSource2Metrics_MatchPerfSummary_Notification)(nil),        // 5: CSource2Metrics_MatchPerfSummary_Notification
	(*CMsgSource2PerfIntervalSample_Tag)(nil),                    // 6: CMsgSource2PerfIntervalSample.Tag
	(*CSource2Metrics_MatchPerfSummary_Notification_Client)(nil), // 7: CSource2Metrics_MatchPerfSummary_Notification.Client
}
var file_source2_steam_stats_proto_depIdxs = []int32{
	1,  // 0: CMsgSource2VProfLiteReport.total:type_name -> CMsgSource2VProfLiteReportItem
	1,  // 1: CMsgSource2VProfLiteReport.items:type_name -> CMsgSource2VProfLiteReportItem
	6,  // 2: CMsgSource2PerfIntervalSample.tags:type_name -> CMsgSource2PerfIntervalSample.Tag
	2,  // 3: CSource2Metrics_MatchPerfSummary_Notification.server_profile:type_name -> CMsgSource2VProfLiteReport
	7,  // 4: CSource2Metrics_MatchPerfSummary_Notification.clients:type_name -> CSource2Metrics_MatchPerfSummary_Notification.Client
	0,  // 5: CSource2Metrics_MatchPerfSummary_Notification.Client.system_specs:type_name -> CMsgSource2SystemSpecs
	2,  // 6: CSource2Metrics_MatchPerfSummary_Notification.Client.profile:type_name -> CMsgSource2VProfLiteReport
	3,  // 7: CSource2Metrics_MatchPerfSummary_Notification.Client.downstream_flow:type_name -> CMsgSource2NetworkFlowQuality
	3,  // 8: CSource2Metrics_MatchPerfSummary_Notification.Client.upstream_flow:type_name -> CMsgSource2NetworkFlowQuality
	4,  // 9: CSource2Metrics_MatchPerfSummary_Notification.Client.perf_samples:type_name -> CMsgSource2PerfIntervalSample
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_source2_steam_stats_proto_init() }
func file_source2_steam_stats_proto_init() {
	if File_source2_steam_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_source2_steam_stats_proto_rawDesc), len(file_source2_steam_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_source2_steam_stats_proto_goTypes,
		DependencyIndexes: file_source2_steam_stats_proto_depIdxs,
		MessageInfos:      file_source2_steam_stats_proto_msgTypes,
	}.Build()
	File_source2_steam_stats_proto = out.File
	file_source2_steam_stats_proto_goTypes = nil
	file_source2_steam_stats_proto_depIdxs = nil
}
