// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: valveextensions.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EProtoDebugVisiblity int32

const (
	EProtoDebugVisiblity_k_EProtoDebugVisibility_Always      EProtoDebugVisiblity = 0
	EProtoDebugVisiblity_k_EProtoDebugVisibility_Server      EProtoDebugVisiblity = 70
	EProtoDebugVisiblity_k_EProtoDebugVisibility_ValveServer EProtoDebugVisiblity = 80
	EProtoDebugVisiblity_k_EProtoDebugVisibility_GC          EProtoDebugVisiblity = 90
	EProtoDebugVisiblity_k_EProtoDebugVisibility_Never       EProtoDebugVisiblity = 100
)

// Enum value maps for EProtoDebugVisiblity.
var (
	EProtoDebugVisiblity_name = map[int32]string{
		0:   "k_EProtoDebugVisibility_Always",
		70:  "k_EProtoDebugVisibility_Server",
		80:  "k_EProtoDebugVisibility_ValveServer",
		90:  "k_EProtoDebugVisibility_GC",
		100: "k_EProtoDebugVisibility_Never",
	}
	EProtoDebugVisiblity_value = map[string]int32{
		"k_EProtoDebugVisibility_Always":      0,
		"k_EProtoDebugVisibility_Server":      70,
		"k_EProtoDebugVisibility_ValveServer": 80,
		"k_EProtoDebugVisibility_GC":          90,
		"k_EProtoDebugVisibility_Never":       100,
	}
)

func (x EProtoDebugVisiblity) Enum() *EProtoDebugVisiblity {
	p := new(EProtoDebugVisiblity)
	*p = x
	return p
}

func (x EProtoDebugVisiblity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EProtoDebugVisiblity) Descriptor() protoreflect.EnumDescriptor {
	return file_valveextensions_proto_enumTypes[0].Descriptor()
}

func (EProtoDebugVisiblity) Type() protoreflect.EnumType {
	return &file_valveextensions_proto_enumTypes[0]
}

func (x EProtoDebugVisiblity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EProtoDebugVisiblity) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EProtoDebugVisiblity(num)
	return nil
}

// Deprecated: Use EProtoDebugVisiblity.Descriptor instead.
func (EProtoDebugVisiblity) EnumDescriptor() ([]byte, []int) {
	return file_valveextensions_proto_rawDescGZIP(), []int{0}
}

var file_valveextensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61000,
		Name:          "codegen_delta_encoder",
		Tag:           "varint,61000,opt,name=codegen_delta_encoder,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61000,
		Name:          "valve_map_field",
		Tag:           "varint,61000,opt,name=valve_map_field,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61001,
		Name:          "valve_map_key",
		Tag:           "varint,61001,opt,name=valve_map_key,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         61002,
		Name:          "diff_encode_field",
		Tag:           "varint,61002,opt,name=diff_encode_field,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61003,
		Name:          "delta_ignore",
		Tag:           "varint,61003,opt,name=delta_ignore,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         61008,
		Name:          "untrusted_delta_max",
		Tag:           "varint,61008,opt,name=untrusted_delta_max,def=256",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         61004,
		Name:          "steamml_max_entries",
		Tag:           "varint,61004,opt,name=steamml_max_entries,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61005,
		Name:          "steamml_is_timestamp",
		Tag:           "varint,61005,opt,name=steamml_is_timestamp,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         61006,
		Name:          "steamlearn_count",
		Tag:           "varint,61006,opt,name=steamlearn_count,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EProtoDebugVisiblity)(nil),
		Field:         61007,
		Name:          "debugprint_visibility",
		Tag:           "varint,61007,opt,name=debugprint_visibility,enum=EProtoDebugVisiblity,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1000,
		Name:          "schema_friendly_name",
		Tag:           "bytes,1000,opt,name=schema_friendly_name",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1001,
		Name:          "schema_description",
		Tag:           "bytes,1001,opt,name=schema_description",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1002,
		Name:          "schema_suppress_enumerator",
		Tag:           "varint,1002,opt,name=schema_suppress_enumerator",
		Filename:      "valveextensions.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool codegen_delta_encoder = 61000;
	E_CodegenDeltaEncoder = &file_valveextensions_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool valve_map_field = 61000;
	E_ValveMapField = &file_valveextensions_proto_extTypes[1]
	// optional bool valve_map_key = 61001;
	E_ValveMapKey = &file_valveextensions_proto_extTypes[2]
	// optional int32 diff_encode_field = 61002;
	E_DiffEncodeField = &file_valveextensions_proto_extTypes[3]
	// optional bool delta_ignore = 61003;
	E_DeltaIgnore = &file_valveextensions_proto_extTypes[4]
	// optional int32 untrusted_delta_max = 61008;
	E_UntrustedDeltaMax = &file_valveextensions_proto_extTypes[5]
	// optional uint32 steamml_max_entries = 61004;
	E_SteammlMaxEntries = &file_valveextensions_proto_extTypes[6]
	// optional bool steamml_is_timestamp = 61005;
	E_SteammlIsTimestamp = &file_valveextensions_proto_extTypes[7]
	// optional uint32 steamlearn_count = 61006;
	E_SteamlearnCount = &file_valveextensions_proto_extTypes[8]
	// optional EProtoDebugVisiblity debugprint_visibility = 61007;
	E_DebugprintVisibility = &file_valveextensions_proto_extTypes[9]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string schema_friendly_name = 1000;
	E_SchemaFriendlyName = &file_valveextensions_proto_extTypes[10]
	// optional string schema_description = 1001;
	E_SchemaDescription = &file_valveextensions_proto_extTypes[11]
	// optional bool schema_suppress_enumerator = 1002;
	E_SchemaSuppressEnumerator = &file_valveextensions_proto_extTypes[12]
)

var File_valveextensions_proto protoreflect.FileDescriptor

const file_valveextensions_proto_rawDesc = "" +
	"\n" +
	"\x15valveextensions.proto\x1a google/protobuf/descriptor.proto*\xca\x01\n" +
	"\x14EProtoDebugVisiblity\x12\"\n" +
	"\x1ek_EProtoDebugVisibility_Always\x10\x00\x12\"\n" +
	"\x1ek_EProtoDebugVisibility_Server\x10F\x12'\n" +
	"#k_EProtoDebugVisibility_ValveServer\x10P\x12\x1e\n" +
	"\x1ak_EProtoDebugVisibility_GC\x10Z\x12!\n" +
	"\x1dk_EProtoDebugVisibility_Never\x10d:\\\n" +
	"\x15codegen_delta_encoder\x12\x1f.google.protobuf.MessageOptions\x18\xc8\xdc\x03 \x01(\b:\x05falseR\x13codegenDeltaEncoder:N\n" +
	"\x0fvalve_map_field\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\b:\x05falseR\rvalveMapField:J\n" +
	"\rvalve_map_key\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\b:\x05falseR\vvalveMapKey:N\n" +
	"\x11diff_encode_field\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x05:\x010R\x0fdiffEncodeField:I\n" +
	"\fdelta_ignore\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\b:\x05falseR\vdeltaIgnore:T\n" +
	"\x13untrusted_delta_max\x12\x1d.google.protobuf.FieldOptions\x18\xd0\xdc\x03 \x01(\x05:\x03256R\x11untrustedDeltaMax:R\n" +
	"\x13steamml_max_entries\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdc\x03 \x01(\r:\x010R\x11steammlMaxEntries:X\n" +
	"\x14steamml_is_timestamp\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xdc\x03 \x01(\b:\x05falseR\x12steammlIsTimestamp:M\n" +
	"\x10steamlearn_count\x12\x1d.google.protobuf.FieldOptions\x18\xce\xdc\x03 \x01(\r:\x010R\x0fsteamlearnCount:\x8b\x01\n" +
	"\x15debugprint_visibility\x12\x1d.google.protobuf.FieldOptions\x18\xcf\xdc\x03 \x01(\x0e2\x15.EProtoDebugVisiblity:\x1ek_EProtoDebugVisibility_AlwaysR\x14debugprintVisibility:T\n" +
	"\x14schema_friendly_name\x12!.google.protobuf.EnumValueOptions\x18\xe8\a \x01(\tR\x12schemaFriendlyName:Q\n" +
	"\x12schema_description\x12!.google.protobuf.EnumValueOptions\x18\xe9\a \x01(\tR\x11schemaDescription:`\n" +
	"\x1aschema_suppress_enumerator\x12!.google.protobuf.EnumValueOptions\x18\xea\a \x01(\bR\x18schemaSuppressEnumerator"

var (
	file_valveextensions_proto_rawDescOnce sync.Once
	file_valveextensions_proto_rawDescData []byte
)

func file_valveextensions_proto_rawDescGZIP() []byte {
	file_valveextensions_proto_rawDescOnce.Do(func() {
		file_valveextensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valveextensions_proto_rawDesc), len(file_valveextensions_proto_rawDesc)))
	})
	return file_valveextensions_proto_rawDescData
}

var file_valveextensions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_valveextensions_proto_goTypes = []any{
	(EProtoDebugVisiblity)(0),             // 0: EProtoDebugVisiblity
	(*descriptorpb.MessageOptions)(nil),   // 1: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),     // 2: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_valveextensions_proto_depIdxs = []int32{
	1,  // 0: codegen_delta_encoder:extendee -> google.protobuf.MessageOptions
	2,  // 1: valve_map_field:extendee -> google.protobuf.FieldOptions
	2,  // 2: valve_map_key:extendee -> google.protobuf.FieldOptions
	2,  // 3: diff_encode_field:extendee -> google.protobuf.FieldOptions
	2,  // 4: delta_ignore:extendee -> google.protobuf.FieldOptions
	2,  // 5: untrusted_delta_max:extendee -> google.protobuf.FieldOptions
	2,  // 6: steamml_max_entries:extendee -> google.protobuf.FieldOptions
	2,  // 7: steamml_is_timestamp:extendee -> google.protobuf.FieldOptions
	2,  // 8: steamlearn_count:extendee -> google.protobuf.FieldOptions
	2,  // 9: debugprint_visibility:extendee -> google.protobuf.FieldOptions
	3,  // 10: schema_friendly_name:extendee -> google.protobuf.EnumValueOptions
	3,  // 11: schema_description:extendee -> google.protobuf.EnumValueOptions
	3,  // 12: schema_suppress_enumerator:extendee -> google.protobuf.EnumValueOptions
	0,  // 13: debugprint_visibility:type_name -> EProtoDebugVisiblity
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	13, // [13:14] is the sub-list for extension type_name
	0,  // [0:13] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_valveextensions_proto_init() }
func file_valveextensions_proto_init() {
	if File_valveextensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valveextensions_proto_rawDesc), len(file_valveextensions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 13,
			NumServices:   0,
		},
		GoTypes:           file_valveextensions_proto_goTypes,
		DependencyIndexes: file_valveextensions_proto_depIdxs,
		EnumInfos:         file_valveextensions_proto_enumTypes,
		ExtensionInfos:    file_valveextensions_proto_extTypes,
	}.Build()
	File_valveextensions_proto = out.File
	file_valveextensions_proto_goTypes = nil
	file_valveextensions_proto_depIdxs = nil
}
