run:
  deadline: 5m
  build-tags:
    - debugdemoinfocs
  skip-dirs:
    - msg
  skip-files:
    - parser_interface.go
    - game_state_interface.go
linters:
  enable-all: true
  disable:
    - gochecknoinits
    - gochecknoglobals
    - lll
    - typecheck
    - gomnd
    - exhaustivestruct
    - godot
    - gofumpt
    - testpackage
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - wsl
        - funlen
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gci:
    local-prefixes: github.com/markus-wa/demoinfocs-golang/v2
