# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "convex-hull"
  name = "github.com/golang/geo"
  source = "github.com/markus-wa/geo"

[[constraint]]
  name = "github.com/markus-wa/gobitread"
  version = "0.2.1"

[[constraint]]
  name = "github.com/markus-wa/godispatch"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/llgcode/draw2d"

[prune]
  go-tests = true
  unused-packages = true
